# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("expense", "Expense"),
                            ("investment", "Investment"),
                            ("withdrawal", "Withdrawal"),
                            ("fine_waiver", "Fine Waiver"),
                            ("role_change", "Role Change"),
                            ("rule_change", "Rule Change"),
                            ("contribution_adjustment", "Contribution Adjustment"),
                            ("member_admission", "Member Admission"),
                            ("member_expulsion", "Member Expulsion"),
                            ("budget", "Budget"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        help_text="Model name this approval is for (e.g., 'Loan', 'Expense')",
                        max_length=100,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(help_text="ID of the object being approved"),
                ),
                (
                    "reference_display",
                    models.CharField(
                        help_text="Human-readable reference (e.g., 'Loan #123')",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "required_level",
                    models.CharField(
                        choices=[
                            ("first", "First Approval"),
                            ("second", "Second Approval"),
                            ("final", "Final Approval"),
                        ],
                        default="first",
                        max_length=20,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("first", "First Approval"),
                            ("second", "Second Approval"),
                            ("final", "Final Approval"),
                        ],
                        default="first",
                        max_length=20,
                    ),
                ),
                (
                    "first_level_approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Role required for first level approval (e.g., 'treasurer')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "second_level_approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Role required for second level approval (e.g., 'chairperson')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "first_level_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount threshold for first level approval",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for approval decision",
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("first", "First Approval"),
                            ("second", "Second Approval"),
                            ("final", "Final Approval"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approver_role", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions attached to approval (e.g., 'must submit collateral')",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="governance.approvalrequest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_steps_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChamaRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("constitution", "Constitution"),
                            ("contributions", "Contributions"),
                            ("meetings", "Meetings"),
                            ("loans", "Loans"),
                            ("fines", "Fines"),
                            ("investments", "Investments"),
                            ("withdrawals", "Withdrawals"),
                            ("membership", "Membership"),
                            ("voting", "Voting"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(help_text="Rule content in markdown format"),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("requires_acknowledgment", models.BooleanField(default=False)),
                (
                    "acknowledgment_deadline_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days within which members must acknowledge",
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="governance.chamarule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleChange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("demotion", "Demotion"),
                            ("resignation", "Resignation"),
                            ("revocation", "Revocation"),
                            ("acting", "Acting Role"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_role", models.CharField(blank=True, max_length=50)),
                ("new_role", models.CharField(max_length=50)),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when the role change takes effect"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the role change expires (for acting roles)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("effective", "Effective"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_acting",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an acting/temporary role",
                    ),
                ),
                (
                    "acting_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for acting role (e.g., 'primary holder on leave')",
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes",
                        to="governance.approvalrequest",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_changes",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleDelegation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("can_delegate_further", models.BooleanField(default=False)),
                (
                    "restrictions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Specific restrictions on delegation (e.g., cannot approve loans over 100k)",
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_role_delegations",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        help_text="Person receiving delegation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        help_text="Original role holder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RuleAcknowledgment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="governance.chamarule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["chama", "approval_type", "status"],
                name="governance__chama_i_bc6825_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requested_by", "status"], name="governance__request_04d3be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="governance__referen_8977cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["due_date", "status"], name="governance__due_dat_a663cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["approval_request", "level"],
                name="governance__approva_1df1e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["decided_by", "status"], name="governance__decided_7cbdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chamarule",
            index=models.Index(
                fields=["chama", "category", "status"],
                name="governance__chama_i_f14658_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chamarule",
            index=models.Index(
                fields=["chama", "effective_date"],
                name="governance__chama_i_696389_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chamarule",
            index=models.Index(
                fields=["status", "effective_date"],
                name="governance__status_fa4307_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chamarule",
            constraint=models.UniqueConstraint(
                fields=("chama", "category", "version"),
                name="unique_rule_version_per_category",
            ),
        ),
        migrations.AddIndex(
            model_name="rolechange",
            index=models.Index(
                fields=["chama", "member", "status"],
                name="governance__chama_i_297d0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolechange",
            index=models.Index(
                fields=["chama", "new_role", "status"],
                name="governance__chama_i_130f29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolechange",
            index=models.Index(
                fields=["expiry_date", "status"], name="governance__expiry__0414de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolechange",
            index=models.Index(
                fields=["effective_date", "status"],
                name="governance__effecti_8b0795_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["chama", "delegate", "is_active"],
                name="governance__chama_i_4c5445_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["delegator", "is_active"], name="governance__delegat_51650b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["end_date", "is_active"], name="governance__end_dat_db7e47_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roledelegation",
            constraint=models.UniqueConstraint(
                fields=("chama", "delegator", "delegate", "role", "start_date"),
                name="unique_delegation",
            ),
        ),
        migrations.AddIndex(
            model_name="ruleacknowledgment",
            index=models.Index(
                fields=["rule", "status"], name="governance__rule_id_296a55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleacknowledgment",
            index=models.Index(
                fields=["member", "status"], name="governance__member__31faab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleacknowledgment",
            constraint=models.UniqueConstraint(
                fields=("rule", "member"), name="unique_acknowledgment_per_rule_member"
            ),
        ),
    ]
