# Generated by Django 5.1.6 on 2026-03-31 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_motion_voting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='motion',
            new_name='governance__chama_i_aa32d4_idx',
            old_name='governance_motion_chama_i_8d027e_idx',
        ),
        migrations.RenameIndex(
            model_name='motion',
            new_name='governance__chama_i_dcf55a_idx',
            old_name='governance_motion_chama_i_0b1d67_idx',
        ),
        migrations.RenameIndex(
            model_name='motionvote',
            new_name='governance__motion__aad8d0_idx',
            old_name='governance_motionv_motion__6b447f_idx',
        ),
        migrations.RenameIndex(
            model_name='motionvote',
            new_name='governance__user_id_b4e551_idx',
            old_name='governance_motionv_user_id_caf7cb_idx',
        ),
        migrations.AlterField(
            model_name='motion',
            name='eligible_roles',
            field=models.JSONField(blank=True, default=list, help_text='Optional role filter for eligible voters.'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motionresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motionresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motionvote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motionvote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
