# Generated by Django 5.1.6 on 2026-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_rename_governance_motion_chama_i_8d027e_idx_governance__chama_i_aa32d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='vote_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Vote'), ('special', 'Special Vote (2/3 majority)'), ('unanimous', 'Unanimous Vote')], default='ordinary', max_length=20),
        ),
    ]
