# Generated by Django 6.0.4 on 2026-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_motion_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('expense', 'Expense'), ('investment', 'Investment'), ('withdrawal', 'Withdrawal'), ('payout', 'Payout'), ('fine_waiver', 'Fine Waiver'), ('role_change', 'Role Change'), ('rule_change', 'Rule Change'), ('contribution_adjustment', 'Contribution Adjustment'), ('member_admission', 'Member Admission'), ('member_expulsion', 'Member Expulsion'), ('budget', 'Budget'), ('other', 'Other')], max_length=30),
        ),
    ]
