# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("chama", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercard",
            name="chama",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_cards",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="membercard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberkyc",
            name="chama",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_records",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="memberkyc",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberkyc",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otpdeliverylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="otp_delivery_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otptoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otpdeliverylog",
            name="otp_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_logs",
                to="accounts.otptoken",
            ),
        ),
        migrations.AddField(
            model_name="passwordhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referred_chama",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_reward",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="rewarded_chama",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_referral_rewards",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="active_chama",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user_preferences",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="accounts_us_phone_f54457_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_verified"], name="accounts_us_phone_v_f7ff44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["created_at"], name="accounts_lo_created_702ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["success", "created_at"], name="accounts_lo_success_4754a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(
                fields=["identifier_attempted", "created_at"],
                name="accounts_lo_identif_4b5675_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membercard",
            index=models.Index(
                fields=["chama", "is_active"], name="accounts_me_chama_i_f24d5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membercard",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_me_user_id_3c050c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membercard",
            index=models.Index(
                fields=["card_number"], name="accounts_me_card_nu_b9a3c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membercard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "chama"),
                name="uniq_active_member_card_per_user_chama",
            ),
        ),
        migrations.AddIndex(
            model_name="memberkyc",
            index=models.Index(
                fields=["chama", "status"], name="accounts_me_chama_i_e98afa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberkyc",
            index=models.Index(
                fields=["user", "status"], name="accounts_me_user_id_690737_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberkyc",
            constraint=models.UniqueConstraint(
                fields=("user", "chama"), name="uniq_member_kyc_per_user_chama"
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["phone", "purpose", "is_used"],
                name="accounts_ot_phone_000ecd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["code_hash", "purpose"], name="accounts_ot_code_ha_1e7639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["expires_at"], name="accounts_ot_expires_4348db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["phone", "created_at"], name="accounts_ot_phone_c5e3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpdeliverylog",
            index=models.Index(
                fields=["otp_token", "channel", "created_at"],
                name="accounts_ot_otp_tok_711dac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpdeliverylog",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_ot_status_8a16b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpdeliverylog",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_ot_user_id_d49c64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_pa_user_id_a6f7e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_pa_user_id_8cd138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expires_at"], name="accounts_pa_expires_01b447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["used_at"], name="accounts_pa_used_at_6bdbd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["referrer", "status"], name="accounts_re_referre_5fc9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["rewarded_chama", "status"],
                name="accounts_re_rewarde_65a3a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["active_chama"], name="accounts_us_active__f92a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["low_data_mode"], name="accounts_us_low_dat_5720a6_idx"
            ),
        ),
    ]
