# Generated by Django 5.1.6 on 2026-04-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberkyc',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='mpesa_registered_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='proof_of_address_image',
            field=models.FileField(blank=True, upload_to='kyc/proof_address/'),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='verification_result',
            field=models.JSONField(blank=True, help_text='Stores KYC verification details from Smile Identity', null=True),
        ),
    ]
