# Generated by Django 5.1.6 on 2026-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_memberkyc_enhanced_flow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberkyc',
            name='account_frozen_for_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='last_sanctions_screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='last_sanctions_screening_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='next_reverification_due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='requires_reverification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberkyc',
            name='reverification_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
