# Generated by Django 6.0.4 on 2026-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_email_verified_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otptoken",
            new_name="accounts_ot_identif_be8f2a_idx",
            old_name="accounts_ot_ident_purpose_used_idx",
        ),
        migrations.RenameIndex(
            model_name="otptoken",
            new_name="accounts_ot_identif_ce512b_idx",
            old_name="accounts_ot_ident_created_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_email_v_054104_idx",
            old_name="accounts_us_email_v_3a8c9a_idx",
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verify_phone", "Phone Verification"),
                    ("verify_email", "Email Verification"),
                    ("login_2fa", "Login 2FA"),
                    ("password_reset", "Password Reset"),
                    ("register", "Registration"),
                    ("withdrawal_confirm", "Withdrawal Confirmation"),
                ],
                default="verify_phone",
                max_length=20,
            ),
        ),
    ]
