from __future__ import annotations

from collections import Counter


AUTOMATION_CATALOG = [
    {
        "key": "auth.otp_generation_expiry",
        "category": "Auth & onboarding",
        "name": "OTP generation & expiry",
        "trigger": "event",
        "channels": ["sms", "email"],
        "status": "implemented",
        "notes": "6-digit OTPs expire after 5 minutes with resend and session safeguards.",
    },
    {
        "key": "auth.otp_cooldown_enforcement",
        "category": "Auth & onboarding",
        "name": "OTP cooldown enforcement",
        "trigger": "event",
        "channels": ["sms", "email"],
        "status": "implemented",
        "notes": "60-second cooldown and rolling resend-window enforcement live in OTP service.",
    },
    {
        "key": "auth.kyc_status_webhook_listener",
        "category": "Auth & onboarding",
        "name": "KYC status webhook listener",
        "trigger": "webhook",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Webhook listener updates MemberKYC state from Smile Identity or Onfido callbacks.",
    },
    {
        "key": "auth.kyc_rejection_notification",
        "category": "Auth & onboarding",
        "name": "KYC rejection notification",
        "trigger": "event",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Rejected KYC callbacks notify the member with the provider reason and resubmission prompt.",
    },
    {
        "key": "contributions.reminder_3d",
        "category": "Contribution",
        "name": "Contribution due reminder - 3 days before",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Stage-based reminder run scans unpaid contribution schedules three days before due date.",
    },
    {
        "key": "contributions.reminder_1d",
        "category": "Contribution",
        "name": "Contribution due reminder - 1 day before",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Stage-based reminder run scans unpaid contribution schedules one day before due date.",
    },
    {
        "key": "contributions.reminder_due_morning",
        "category": "Contribution",
        "name": "Contribution due reminder - due date morning",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Due-today reminder stage runs on the scheduled contribution day.",
    },
    {
        "key": "contributions.late_payment_flag",
        "category": "Contribution",
        "name": "Late payment flag",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Pending contribution schedules are marked missed after the grace period.",
    },
    {
        "key": "contributions.penalty_calculation",
        "category": "Contribution",
        "name": "Penalty calculation & application",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Penalties can be auto-issued from automation rule config after missed contributions.",
    },
    {
        "key": "contributions.penalty_notification",
        "category": "Contribution",
        "name": "Penalty notification",
        "trigger": "event",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Penalty issuance creates member notifications with the amount and reason.",
    },
    {
        "key": "contributions.mpesa_stk_callback",
        "category": "Contribution",
        "name": "M-Pesa STK push callback handler",
        "trigger": "webhook",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Safaricom STK callbacks update payment intent state and reconciliation records.",
    },
    {
        "key": "payouts.review_trigger",
        "category": "Payout",
        "name": "Payout trigger",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "partial",
        "notes": "Payment readiness is derivable from contribution schedules, but no dedicated payout-cycle model exists yet.",
    },
    {
        "key": "payouts.rotation_updater",
        "category": "Payout",
        "name": "Payout rotation updater",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "partial",
        "notes": "Rotation logic needs a first-class payout-cycle roster model before it can be automated safely.",
    },
    {
        "key": "payouts.mpesa_b2c_disbursement",
        "category": "Payout",
        "name": "Payout disbursement via M-Pesa B2C",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "B2C disbursement orchestration exists after treasurer/admin approval.",
    },
    {
        "key": "payouts.failure_retry",
        "category": "Payout",
        "name": "Payout failure retry",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Timed-out or failed B2C payouts are retried up to three attempts before escalation.",
    },
    {
        "key": "payouts.completion_notification",
        "category": "Payout",
        "name": "Payout completion notification",
        "trigger": "event",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Recipient and finance leadership receive payout status notifications; group-wide announcement is partial.",
    },
    {
        "key": "loans.eligibility_checker",
        "category": "Loan",
        "name": "Loan eligibility checker",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Contribution history and membership duration feed eligibility checks before loan creation.",
    },
    {
        "key": "loans.application_notification",
        "category": "Loan",
        "name": "Loan application notification",
        "trigger": "event",
        "channels": ["push"],
        "status": "implemented",
        "notes": "New applications can be surfaced to treasurer/admin reviewers from the loan workflow.",
    },
    {
        "key": "loans.decision_notification",
        "category": "Loan",
        "name": "Loan approval/rejection notification",
        "trigger": "event",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Approval and rejection helper notifications are available in the notifications service.",
    },
    {
        "key": "loans.disbursement_b2c",
        "category": "Loan",
        "name": "Loan disbursement via M-Pesa B2C",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Loan disbursement sends B2C payouts through the payment workflow.",
    },
    {
        "key": "loans.repayment_schedule_generator",
        "category": "Loan",
        "name": "Repayment schedule generator",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Schedules are generated after loan approval/disbursement.",
    },
    {
        "key": "loans.repayment_due_reminder",
        "category": "Loan",
        "name": "Repayment due reminder",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Installment reminders already run for due-soon, due-today, and overdue escalation stages.",
    },
    {
        "key": "loans.overdue_flag",
        "category": "Loan",
        "name": "Overdue loan flag",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Overdue installments are marked and delinquency refresh updates loan status.",
    },
    {
        "key": "loans.overdue_penalty",
        "category": "Loan",
        "name": "Overdue penalty application",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Late penalties can be issued automatically from loan penalty settings.",
    },
    {
        "key": "wallet.topup_callback",
        "category": "Wallet",
        "name": "M-Pesa top-up callback handler",
        "trigger": "webhook",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Incoming payment callbacks update wallet/payment state through the payment workflow.",
    },
    {
        "key": "wallet.withdrawal_b2c",
        "category": "Wallet",
        "name": "Wallet withdrawal via M-Pesa B2C",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Wallet withdrawal intents feed the shared B2C payout flow.",
    },
    {
        "key": "wallet.withdrawal_eligibility",
        "category": "Wallet",
        "name": "Withdrawal eligibility check",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Withdrawal requests validate available balance, penalties, and overdue loans before locking funds.",
    },
    {
        "key": "wallet.member_transfer",
        "category": "Wallet",
        "name": "Member-to-member transfer",
        "trigger": "event",
        "channels": ["push"],
        "status": "partial",
        "notes": "Wallet primitives exist, but there is no dedicated member-transfer workflow yet.",
    },
    {
        "key": "meetings.reminder_1w",
        "category": "Meeting",
        "name": "Meeting reminder - 1 week before",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Scheduled scan reminds invited members seven days before the meeting.",
    },
    {
        "key": "meetings.reminder_24h",
        "category": "Meeting",
        "name": "Meeting reminder - 24 hours before",
        "trigger": "schedule",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Scheduled scan reminds invited members 24 hours before the meeting.",
    },
    {
        "key": "meetings.reminder_1h",
        "category": "Meeting",
        "name": "Meeting reminder - 1 hour before",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Scheduled scan reminds active invitees one hour before the meeting.",
    },
    {
        "key": "meetings.rsvp_nudge",
        "category": "Meeting",
        "name": "RSVP non-responder nudge",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Members without an attendance response are nudged 48 hours before the meeting.",
    },
    {
        "key": "meetings.next_auto_schedule",
        "category": "Meeting",
        "name": "Next meeting auto-scheduler",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Closed/past meetings can seed the next placeholder meeting from chama meeting frequency settings.",
    },
    {
        "key": "announcements.scheduled_dispatch",
        "category": "Announcement",
        "name": "Scheduled announcement dispatcher",
        "trigger": "schedule",
        "channels": ["in_app", "sms", "email"],
        "status": "implemented",
        "notes": "Scheduled announcement records are marked dispatched when due notifications are released.",
    },
    {
        "key": "announcements.unread_followup",
        "category": "Announcement",
        "name": "Unread follow-up reminder",
        "trigger": "schedule",
        "channels": ["sms"],
        "status": "implemented",
        "notes": "Unread high/critical broadcasts trigger a follow-up reminder after 24 hours.",
    },
    {
        "key": "announcements.bulk_sms_batch",
        "category": "Announcement",
        "name": "Bulk SMS batch sender",
        "trigger": "schedule",
        "channels": ["sms"],
        "status": "partial",
        "notes": "Broadcast notifications fan out asynchronously, but explicit SMS batching is still provider-rate-limit dependent.",
    },
    {
        "key": "announcements.deep_links",
        "category": "Announcement",
        "name": "Deep link generator",
        "trigger": "event",
        "channels": ["push", "email", "sms"],
        "status": "implemented",
        "notes": "Notifications are enriched with deep and universal links from the deep-link service.",
    },
    {
        "key": "issues.auto_issue_creator",
        "category": "Issue",
        "name": "System auto-issue creator",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Missed payments, overdue loans, and quorum failures can automatically raise issues.",
    },
    {
        "key": "issues.assignment_notification",
        "category": "Issue",
        "name": "Issue assignment notification",
        "trigger": "event",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Assigned handlers receive issue assignment notifications.",
    },
    {
        "key": "issues.clarification_notification",
        "category": "Issue",
        "name": "Clarification request notification",
        "trigger": "event",
        "channels": ["push"],
        "status": "partial",
        "notes": "Issue comments exist, but a dedicated clarification-request workflow is not modelled yet.",
    },
    {
        "key": "issues.resolution_notification",
        "category": "Issue",
        "name": "Issue resolution notification",
        "trigger": "event",
        "channels": ["push", "sms"],
        "status": "implemented",
        "notes": "Issue raisers receive resolution/closure notifications.",
    },
    {
        "key": "governance.voting_period_opener",
        "category": "Governance",
        "name": "Voting period opener",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Eligible members are notified when a motion enters its voting window.",
    },
    {
        "key": "governance.voting_reminder",
        "category": "Governance",
        "name": "Voting reminder",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Non-voters are nudged 24 hours before a motion deadline.",
    },
    {
        "key": "governance.voting_period_closer",
        "category": "Governance",
        "name": "Voting period closer",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Expired motions are tallied and closed automatically.",
    },
    {
        "key": "governance.nomination_deadline_enforcer",
        "category": "Governance",
        "name": "Election nomination deadline enforcer",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "blocked",
        "notes": "The codebase does not yet contain nomination/candidate models to enforce.",
    },
    {
        "key": "governance.role_permissions_updater",
        "category": "Governance",
        "name": "Role change permissions updater",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Approved role changes are applied and expired acting roles are reverted against memberships.",
    },
    {
        "key": "notifications.push_retry",
        "category": "Notification delivery",
        "name": "Push notification retry",
        "trigger": "schedule",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Failed push deliveries are retried without dropping the in-app notification.",
    },
    {
        "key": "notifications.sms_retry",
        "category": "Notification delivery",
        "name": "SMS retry",
        "trigger": "schedule",
        "channels": ["sms"],
        "status": "implemented",
        "notes": "SMS retries are handled through the notification retry queue and provider delivery logs.",
    },
    {
        "key": "notifications.email_retry",
        "category": "Notification delivery",
        "name": "Email retry",
        "trigger": "schedule",
        "channels": ["email"],
        "status": "implemented",
        "notes": "Email retries are handled through the notification retry queue and provider delivery logs.",
    },
    {
        "key": "notifications.read_receipt_tracker",
        "category": "Notification delivery",
        "name": "Notification read receipt tracker",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Read receipts are stored with timestamps when notifications are opened.",
    },
    {
        "key": "notifications.badge_count_updater",
        "category": "Notification delivery",
        "name": "Badge count updater",
        "trigger": "event",
        "channels": ["push"],
        "status": "implemented",
        "notes": "Unread count is attached to push deliveries as the badge value.",
    },
    {
        "key": "reporting.monthly_financial_report",
        "category": "Reporting & export",
        "name": "Monthly financial report generator",
        "trigger": "schedule",
        "channels": ["email"],
        "status": "implemented",
        "notes": "Monthly report generation and report-run tasks already exist.",
    },
    {
        "key": "reporting.audit_log_writer",
        "category": "Reporting & export",
        "name": "Audit log writer",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Audit logs are written across governance, finance, roles, and notifications.",
    },
    {
        "key": "reporting.receipt_pdf_generator",
        "category": "Reporting & export",
        "name": "Receipt PDF generator",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "partial",
        "notes": "Report and PDF primitives exist, but transaction receipt PDFs are not a dedicated payment workflow yet.",
    },
    {
        "key": "reporting.invoice_generator",
        "category": "Reporting & export",
        "name": "Invoice generator",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Billing invoice creation is already modelled for payment initiation flows.",
    },
    {
        "key": "maintenance.jwt_refresh",
        "category": "System maintenance",
        "name": "JWT token refresh",
        "trigger": "event",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Refresh-token flow is already exposed by the auth API.",
    },
    {
        "key": "maintenance.session_cleanup",
        "category": "System maintenance",
        "name": "Session cleanup",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Expired OTPs, stale sessions, and lockouts are cleaned on schedule.",
    },
    {
        "key": "maintenance.health_check_pinger",
        "category": "System maintenance",
        "name": "Health check pinger",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "implemented",
        "notes": "Maintenance task pings API/database/cache/provider health from Celery.",
    },
    {
        "key": "maintenance.data_backup_scheduler",
        "category": "System maintenance",
        "name": "Data backup scheduler",
        "trigger": "schedule",
        "channels": ["in_app"],
        "status": "partial",
        "notes": "Task support exists, but real database backups still depend on pg_dump availability and deployment credentials.",
    },
]


def get_automation_catalog() -> dict:
    category_counts = Counter(item["category"] for item in AUTOMATION_CATALOG)
    status_counts = Counter(item["status"] for item in AUTOMATION_CATALOG)
    return {
        "summary": {
            "total": len(AUTOMATION_CATALOG),
            "by_category": dict(sorted(category_counts.items())),
            "by_status": dict(sorted(status_counts.items())),
        },
        "items": AUTOMATION_CATALOG,
    }
