# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_identifier", models.CharField(db_index=True, max_length=255)),
                ("locked_until", models.DateTimeField(db_index=True)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_account_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_identifier", "locked_until"],
                        name="security_ac_user_id_608238_idx",
                    ),
                    models.Index(
                        fields=["user", "locked_until"],
                        name="security_ac_user_id_085aac_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("action_type", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chama", "action_type", "created_at"],
                        name="security_au_chama_i_c4be93_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="security_au_actor_i_a5fe48_idx",
                    ),
                    models.Index(
                        fields=["target_type", "created_at"],
                        name="security_au_target__79223b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_sessions",
                        to="chama.chama",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_revoked", "last_seen"],
                        name="security_de_user_id_2be977_idx",
                    ),
                    models.Index(
                        fields=["chama", "is_revoked", "last_seen"],
                        name="security_de_chama_i_f871f7_idx",
                    ),
                    models.Index(
                        fields=["session_key", "is_revoked"],
                        name="security_de_session_769d8a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_identifier", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_identifier", "created_at"],
                        name="security_lo_user_id_c0e698_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="security_lo_ip_addr_7e4e10_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="security_lo_success_77e52e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SUSPICIOUS_LOGIN", "Suspicious Login"),
                            ("MULTIPLE_FAILED_LOGINS", "Multiple Failed Logins"),
                            ("UNUSUAL_LOCATION", "Unusual Location"),
                            ("DEVICE_COMPROMISED", "Device Compromised"),
                            ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                            ("PAYMENT_ANOMALY", "Payment Anomaly"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("TOKEN_EXPIRED", "Token Expired"),
                            ("API_ABUSE", "API Abuse"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_resolved"],
                        name="security_se_user_id_0a4fd1_idx",
                    ),
                    models.Index(
                        fields=["chama", "is_resolved"],
                        name="security_se_chama_i_0b0183_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "created_at"],
                        name="security_se_alert_t_df8e26_idx",
                    ),
                    models.Index(
                        fields=["level", "is_resolved"],
                        name="security_se_level_d6d194_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                (
                    "device_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "last_activity",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "chama_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_user_sessions",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="security_us_user_id_9aa362_idx",
                    ),
                    models.Index(
                        fields=["user", "last_activity"],
                        name="security_us_user_id_eb55e9_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="security_us_expires_f5812f_idx"
                    ),
                ],
            },
        ),
    ]
