# Generated by Django 5.1.6 on 2026-03-31 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_rbac_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['locked_until'], name='security_ac_locked__e85066_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceLoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'success', 'created_at'], name='security_de_user_id_1fbd7c_idx'), models.Index(fields=['ip_address', 'created_at'], name='security_de_ip_addr_54bd3b_idx'), models.Index(fields=['fingerprint', 'created_at'], name='security_de_fingerp_c25d57_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('device_trusted', 'Device Trusted'), ('device_revoked', 'Device Revoked'), ('suspicious_activity', 'Suspicious Activity'), ('session_expired', 'Session Expired'), ('token_refreshed', 'Token Refreshed')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='security_se_user_id_f7052a_idx'), models.Index(fields=['event_type', 'created_at'], name='security_se_event_t_18b5ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'fingerprint'], name='security_tr_user_id_c7af4c_idx'), models.Index(fields=['user', 'is_trusted'], name='security_tr_user_id_5efe5b_idx'), models.Index(fields=['expires_at'], name='security_tr_expires_83530c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'fingerprint'), name='unique_user_device_fingerprint')],
            },
        ),
    ]
