# Generated by Django 5.1.6 on 2026-04-20 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_audit_chain_checkpoint_and_pin_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('case_type', models.CharField(choices=[('transaction', 'Transaction Fraud'), ('account', 'Account Takeover'), ('identity', 'Identity Fraud'), ('loan', 'Loan Fraud'), ('aml', 'AML Alert')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('escalated', 'Escalated'), ('resolved_true_positive', 'True Positive'), ('resolved_false_positive', 'False Positive'), ('frozen', 'Account Frozen'), ('released', 'Released')], default='open', max_length=24)),
                ('fraud_score', models.PositiveSmallIntegerField(default=0)),
                ('triggered_by', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('linked_events', models.JSONField(blank=True, default=list)),
                ('resolution_summary', models.TextField(blank=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='security_fr_user_id_7bed66_idx'), models.Index(fields=['status', 'sla_deadline'], name='security_fr_status_4bcf6f_idx'), models.Index(fields=['assigned_to', 'status'], name='security_fr_assigne_f782b5_idx'), models.Index(fields=['severity', 'status'], name='security_fr_severit_bb64c4_idx')],
            },
        ),
    ]
