# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "yearly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "stripe_monthly_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_yearly_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="BillingCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("referral", "Referral Reward"),
                            ("manual", "Manual Credit"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="referral",
                        max_length=20,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_credits",
                        to="chama.chama",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription_created", "Subscription Created"),
                            ("subscription_activated", "Subscription Activated"),
                            ("subscription_canceled", "Subscription Canceled"),
                            ("subscription_paused", "Subscription Paused"),
                            ("subscription_resumed", "Subscription Resumed"),
                            ("plan_changed", "Plan Changed"),
                            ("payment_succeeded", "Payment Succeeded"),
                            ("payment_failed", "Payment Failed"),
                            ("seat_limit_warning", "Seat Limit Warning"),
                            ("seat_limit_exceeded", "Seat Limit Exceeded"),
                            ("feature_override_created", "Feature Override Created"),
                            ("feature_override_removed", "Feature Override Removed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_events",
                        to="chama.chama",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Event",
                "verbose_name_plural": "Billing Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                ("grace_period_days", models.PositiveIntegerField(default=7)),
                (
                    "enforcement_mode",
                    models.CharField(
                        choices=[
                            ("hard_lock", "Hard Lock"),
                            ("soft_lock", "Soft Lock"),
                        ],
                        default="hard_lock",
                        max_length=20,
                    ),
                ),
                (
                    "upgrade_approval_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("auto_renew_enabled", models.BooleanField(default=True)),
                ("payment_retry_schedule", models.JSONField(blank=True, default=list)),
                ("allow_enterprise_overrides", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rule",
                        to="chama.chama",
                    ),
                ),
            ],
            options={
                "ordering": ["chama_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_key", models.CharField(max_length=100)),
                ("value", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_overrides",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Override",
                "verbose_name_plural": "Feature Overrides",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("void", "Void"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("billing_period_start", models.DateTimeField(blank=True, null=True)),
                ("billing_period_end", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="billing/invoices/"
                    ),
                ),
                ("metadata_encrypted", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="chama.chama",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event_type", models.CharField(max_length=80)),
                ("external_event_id", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("verified", models.BooleanField(default=False)),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=8)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "processing_status",
                    models.CharField(default="received", max_length=40),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_webhook_events",
                        to="chama.chama",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingCreditAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("applied", "Applied"),
                            ("released", "Released"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="billing.billingcredit",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_allocations",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SeatUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active_members_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_usage",
                        to="chama.chama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Usage",
                "verbose_name_plural": "Seat Usages",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("canceled", "Canceled"),
                            ("past_due", "Past Due"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("mpesa", "M-Pesa"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("auto_renew", models.BooleanField(default=True)),
                ("grace_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_change_at", models.DateTimeField(blank=True, null=True)),
                ("failed_payment_count", models.PositiveIntegerField(default=0)),
                ("payment_metadata", models.TextField(blank=True, default="")),
                (
                    "last_payment_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("last_invoiced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="chama.chama",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="billing.plan"
                    ),
                ),
                (
                    "scheduled_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.subscription",
            ),
        ),
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        choices=[
                            ("members", "Members"),
                            ("sms", "SMS"),
                            ("otp_sms", "OTP / Security SMS"),
                            ("storage_mb", "Storage (MB)"),
                            ("stk_pushes", "M-Pesa STK Pushes"),
                        ],
                        max_length=40,
                    ),
                ),
                ("used_quantity", models.PositiveIntegerField(default=0)),
                ("limit_quantity", models.PositiveIntegerField(default=0)),
                (
                    "period_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("reset_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="chama.chama",
                    ),
                ),
            ],
            options={
                "ordering": ["metric_key"],
            },
        ),
        migrations.AddIndex(
            model_name="billingcredit",
            index=models.Index(
                fields=["chama", "expires_at"], name="billing_bil_chama_i_4ce010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingcredit",
            index=models.Index(
                fields=["source_type", "source_reference"],
                name="billing_bil_source__5c1ade_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingevent",
            index=models.Index(
                fields=["chama", "created_at"], name="billing_bil_chama__creat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrule",
            index=models.Index(
                fields=["chama", "is_active"], name="billing_bil_chama_i_6beab5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrule",
            index=models.Index(
                fields=["name", "is_active"], name="billing_bil_name_38cba1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureoverride",
            unique_together={("chama", "feature_key")},
        ),
        migrations.AddIndex(
            model_name="billingwebhookevent",
            index=models.Index(
                fields=["provider", "created_at"], name="billing_bil_provide_55f007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingwebhookevent",
            index=models.Index(
                fields=["processing_status", "created_at"],
                name="billing_bil_process_0bb0b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingwebhookevent",
            index=models.Index(
                fields=["external_event_id"], name="billing_bil_externa_d2a546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingcreditallocation",
            index=models.Index(
                fields=["invoice", "status"], name="billing_bil_invoice_ee59b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingcreditallocation",
            index=models.Index(
                fields=["credit", "status"], name="billing_bil_credit__7fe0a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["chama", "status"], name="billing_sub_chama__status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "current_period_end"], name="billing_sub_status_p_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["chama", "status", "created_at"],
                name="billing_inv_chama_i_1f7c54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="billing_inv_provide_85447d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="billing_inv_invoice_70511c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagemetric",
            index=models.Index(
                fields=["chama", "metric_key"], name="billing_usa_chama_i_43b2ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagemetric",
            index=models.Index(
                fields=["period_ends_at"], name="billing_usa_period__22a148_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagemetric",
            unique_together={("chama", "metric_key")},
        ),
    ]
