# Generated by Django 5.1.6 on 2026-03-31 19:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0006_rename_chama_contr_contrib_b3165c_idx_chama_chama_contrib_f4ff8c_idx_and_more'),
        ('finance', '0008_contribution_refund_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='finance_acc_chama_i_d802fa_idx',
            old_name='finance_acc_chama_t_0f4bdc_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='finance_acc_chama_i_488ff7_idx',
            old_name='finance_acc_chama_s_78f196_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_chama_i_5f7277_idx',
            old_name='finance_exp_chama_e_5d9a09_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_chama_i_9028d7_idx',
            old_name='finance_exp_chama_s_9c1ed7_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_categor_095875_idx',
            old_name='finance_exp_catego_d9f389_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='finance_exp_chama_i_2ca24f_idx',
            old_name='finance_expe_chama_i_645ec6_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='finance_exp_chama_i_29fd2a_idx',
            old_name='finance_expe_chama_i_2ef651_idx',
        ),
        migrations.RenameIndex(
            model_name='financialsnapshot',
            new_name='finance_fin_chama_i_ae5de2_idx',
            old_name='finance_sna_chama_s_9a92f4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_chama_i_d58f55_idx',
            old_name='finance_jou_chama_s_9ebcbc_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_referen_036cab_idx',
            old_name='finance_jou_referen_123e47_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='finance_led_journal_720760_idx',
            old_name='finance_led_journal_90ec9c_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='finance_led_account_8445ca_idx',
            old_name='finance_led_account_d4d7d9_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='finance_loa_chama_i_05bd1d_idx',
            old_name='finance_loa_chama_i_b7bf1e_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='finance_loa_status_9ac263_idx',
            old_name='finance_loa_status__5831f4_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplication',
            new_name='finance_loa_chama_i_5181f5_idx',
            old_name='finance_loa_chama_s_ef57c9_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplication',
            new_name='finance_loa_member__312877_idx',
            old_name='finance_loa_member__1501f0_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplication',
            new_name='finance_loa_status_e4e408_idx',
            old_name='finance_loa_status__313174_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplication',
            new_name='finance_loa_loan_pr_22ae2e_idx',
            old_name='finance_loa_loan_pr_366ec3_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplicationapproval',
            new_name='finance_loa_loan_ap_a8f2de_idx',
            old_name='finance_loa_loan_ap_3956ad_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplicationapproval',
            new_name='finance_loa_decisio_2b6038_idx',
            old_name='finance_loa_decisio_010ffc_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplicationguarantor',
            new_name='finance_loa_loan_ap_0e489b_idx',
            old_name='finance_loa_loan_ap_b9eae0_idx',
        ),
        migrations.RenameIndex(
            model_name='loanapplicationguarantor',
            new_name='finance_loa_guarant_660002_idx',
            old_name='finance_loa_guarant_705193_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrecoveryaction',
            new_name='finance_loa_loan_id_3347e5_idx',
            old_name='finance_recovery_loan_act_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrecoveryaction',
            new_name='finance_loa_action__eda141_idx',
            old_name='finance_recovery_action_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrestructure',
            new_name='finance_loa_loan_id_1211ec_idx',
            old_name='finance_restructure_loan_idx',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='rejected_reason',
        ),
        migrations.AddField(
            model_name='loan',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'None'), ('reminder', 'Reminder'), ('warning', 'Warning'), ('escalated', 'Escalated'), ('recovery', 'Recovery')], default='none', help_text='Current escalation level for overdue loan', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='escalation_started_at',
            field=models.DateTimeField(blank=True, help_text='When escalation process started', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='final_status',
            field=models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('restructured', 'Restructured'), ('written_off', 'Written Off'), ('defaulted_recovering', 'Defaulted Recovering'), ('defaulted_unrecovered', 'Defaulted Unrecovered')], default='active', help_text='Final status of the loan', max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='final_status_by',
            field=models.ForeignKey(blank=True, help_text='User who set the final status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_status_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='final_status_date',
            field=models.DateTimeField(blank=True, help_text='When final status was set', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_escalation_sent_at',
            field=models.DateTimeField(blank=True, help_text='When last escalation was sent to admin/treasurer', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When last reminder was sent to borrower', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='recovery_meeting_date',
            field=models.DateField(blank=True, help_text='Date of recovery meeting', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='recovery_meeting_scheduled',
            field=models.BooleanField(default=False, help_text='Whether recovery meeting has been scheduled'),
        ),
        migrations.AddField(
            model_name='loan',
            name='recovery_notes',
            field=models.TextField(blank=True, help_text='Manual recovery notes'),
        ),
        migrations.AddField(
            model_name='loan',
            name='recovery_officer',
            field=models.ForeignKey(blank=True, help_text='Officer assigned to recovery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='write_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount written off', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='write_off_reason',
            field=models.TextField(blank=True, help_text='Reason for write-off'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='exposure_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current exposure amount for this guarantor', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When guarantor was notified about loan status', null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='recovery_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount recovered from guarantor', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='recovery_triggered',
            field=models.BooleanField(default=False, help_text='Whether recovery has been triggered for this guarantor'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='recovery_triggered_at',
            field=models.DateTimeField(blank=True, help_text='When recovery was triggered', null=True),
        ),
        migrations.AddField(
            model_name='loanrecoveryaction',
            name='guarantor',
            field=models.ForeignKey(blank=True, help_text='Guarantor involved in recovery action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to='finance.loanguarantor'),
        ),
        migrations.AddField(
            model_name='loanrecoveryaction',
            name='offset_from_contributions',
            field=models.BooleanField(default=False, help_text='Whether action involved offsetting from contributions'),
        ),
        migrations.AddField(
            model_name='loanrecoveryaction',
            name='offset_from_savings',
            field=models.BooleanField(default=False, help_text='Whether action involved offsetting from savings'),
        ),
        migrations.AddField(
            model_name='loanrecoveryaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_recovery_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installmentschedule',
            name='status',
            field=models.CharField(choices=[('due', 'Due'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('wallet_topup', 'Wallet Top-up'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('withdrawal', 'Withdrawal'), ('expense', 'Expense'), ('fee', 'Fee'), ('penalty', 'Penalty'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('review', 'Review'), ('approved', 'Approved'), ('disbursing', 'Disbursing'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('restructured', 'Restructured'), ('paid', 'Paid'), ('closed', 'Closed'), ('cleared', 'Cleared'), ('defaulted', 'Defaulted'), ('defaulted_recovering', 'Defaulted Recovering'), ('written_off', 'Written Off'), ('recovered_from_offset', 'Recovered From Offset'), ('recovered_from_guarantor', 'Recovered From Guarantor'), ('rejected', 'Rejected')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, db_column='rejected_reason'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplicationapproval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplicationapproval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplicationguarantor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplicationguarantor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapprovallog',
            name='stage',
            field=models.CharField(choices=[('treasurer_review', 'Treasurer Review'), ('committee_approval', 'Committee Approval'), ('admin_approval', 'Admin Approval'), ('disbursement', 'Disbursement')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanrecoveryaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrecoveryaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrestructure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['escalation_level'], name='finance_loa_escalat_330c05_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['chama', 'escalation_level'], name='finance_loa_chama_i_979b82_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['recovery_meeting_scheduled'], name='finance_loa_recover_8a9cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['recovery_officer'], name='finance_loa_recover_21211c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['final_status'], name='finance_loa_final_s_34c708_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['chama', 'final_status'], name='finance_loa_chama_i_d57206_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['final_status_date'], name='finance_loa_final_s_2cd9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['recovery_triggered'], name='finance_loa_recover_89d1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['guarantor', 'recovery_triggered'], name='finance_loa_guarant_de3159_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryaction',
            index=models.Index(fields=['performed_by'], name='finance_loa_perform_828566_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryaction',
            index=models.Index(fields=['guarantor'], name='finance_loa_guarant_149974_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryaction',
            index=models.Index(fields=['offset_from_savings'], name='finance_loa_offset__be03bb_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrecoveryaction',
            index=models.Index(fields=['offset_from_contributions'], name='finance_loa_offset__6bbe8c_idx'),
        ),
    ]
