# Generated by Django 5.1.6 on 2026-04-20 11:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chama", "0007_loanpolicy_block_pending_loan_applications_and_more"),
        (
            "finance",
            "0009_rename_finance_acc_chama_t_0f4bdc_idx_finance_acc_chama_i_d802fa_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("action", models.CharField(max_length=64)),
                ("status_from", models.CharField(blank=True, max_length=30)),
                ("status_to", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="approval_requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="contribution_consistency_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="contribution_count_at_application",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="eligible_amount_at_application",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="installment_estimate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_multiplier_at_application",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="next_steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="repayment_history_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="risk_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="savings_balance_at_application",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="total_repayment_estimate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible_amount_at_application__gte", Decimal("0.00"))
                ),
                name="loan_application_eligible_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("savings_balance_at_application__gte", Decimal("0.00"))
                ),
                name="loan_application_savings_snapshot_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repayment_history_score__gte", Decimal("0.00")),
                    ("repayment_history_score__lte", Decimal("100.00")),
                ),
                name="loan_application_repayment_score_between_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contribution_consistency_score__gte", Decimal("0.00")),
                    ("contribution_consistency_score__lte", Decimal("100.00")),
                ),
                name="loan_application_consistency_score_between_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("installment_estimate__gte", Decimal("0.00"))),
                name="loan_application_installment_estimate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_repayment_estimate__gte", Decimal("0.00"))),
                name="loan_application_total_repayment_estimate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("loan_multiplier_at_application__gte", Decimal("0.00"))
                ),
                name="loan_application_multiplier_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_loan_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="chama",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_audit_logs",
                to="chama.chama",
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="finance.loan",
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="loan_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="finance.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanauditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="loanauditlog",
            index=models.Index(
                fields=["chama", "action", "created_at"],
                name="finance_loa_chama_i_c92504_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanauditlog",
            index=models.Index(
                fields=["member", "action", "created_at"],
                name="finance_loa_member__06a12a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanauditlog",
            index=models.Index(
                fields=["loan_application", "created_at"],
                name="finance_loa_loan_ap_c6acb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanauditlog",
            index=models.Index(
                fields=["loan", "created_at"], name="finance_loa_loan_id_3cf7a1_idx"
            ),
        ),
    ]
