# Generated by Django 5.1.6 on 2026-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_wallet_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationguarantor',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('at_risk', 'At Risk'), ('rejected', 'Rejected'), ('released', 'Released')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('at_risk', 'At Risk'), ('rejected', 'Rejected'), ('released', 'Released')], default='proposed', max_length=20),
        ),
    ]
