# Generated by Django 6.0.4 on 2026-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_installmentschedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet'), ('card', 'Card'), ('other', 'Other')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('wallet_topup', 'Wallet Top-up'), ('wallet_transfer', 'Wallet Transfer'), ('payout', 'Payout'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('withdrawal', 'Withdrawal'), ('expense', 'Expense'), ('fee', 'Fee'), ('penalty', 'Penalty'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet'), ('card', 'Card'), ('other', 'Other')], default='mpesa', max_length=20),
        ),
    ]
