from __future__ import annotations

from apps.notifications.models import (
    NotificationCategory,
    NotificationPriority,
)


def _event(
    key: str,
    *,
    category: str,
    channels: list[str],
    recipients: str,
    schedule: str,
    disableable: bool,
    priority: str,
    source: str,
    variables: list[str],
):
    return {
        "event_name": key,
        "trigger_source": source,
        "allowed_channels": channels,
        "recipient_rules": recipients,
        "schedule_mode": schedule,
        "user_disableable": disableable,
        "template_variables": variables,
        "priority": priority,
        "category": category,
    }


NOTIFICATION_EVENT_CATALOG = [
    _event("otp_requested", category=NotificationCategory.SECURITY, channels=["sms", "email"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.CRITICAL, source="auth.otp_requested", variables=["code", "expires_in_minutes"]),
    _event("welcome_registered_user", category=NotificationCategory.SYSTEM, channels=["email", "in_app"], recipients="new_user", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="auth.user_registered", variables=["full_name"]),
    _event("password_reset_requested", category=NotificationCategory.SECURITY, channels=["sms", "email"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.CRITICAL, source="auth.password_reset_requested", variables=["reset_code", "reset_link", "expires_in_minutes"]),
    _event("suspicious_login_alert", category=NotificationCategory.SECURITY, channels=["email", "in_app"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="auth.suspicious_login_detected", variables=["device_name", "ip_address", "logged_at"]),
    _event("account_verification_success", category=NotificationCategory.SECURITY, channels=["email", "in_app"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.NORMAL, source="auth.account_verified", variables=["full_name"]),
    _event("kyc_submitted", category=NotificationCategory.SECURITY, channels=["email", "in_app"], recipients="target_user_and_reviewers", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="accounts.kyc_submitted", variables=["full_name", "chama_name"]),
    _event("kyc_approved", category=NotificationCategory.SECURITY, channels=["in_app", "email", "sms"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="accounts.kyc_status_changed", variables=["full_name", "chama_name"]),
    _event("kyc_rejected", category=NotificationCategory.SECURITY, channels=["in_app", "email", "sms"], recipients="target_user", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="accounts.kyc_status_changed", variables=["full_name", "reason", "chama_name"]),
    _event("chama_created", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email"], recipients="chama_creator", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="chama.created", variables=["chama_name"]),
    _event("invite_received", category=NotificationCategory.INVITE, channels=["sms", "email", "in_app"], recipients="invitee", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="invite.created", variables=["chama_name", "inviter_name", "invite_link", "invite_code"]),
    _event("invite_resent", category=NotificationCategory.INVITE, channels=["sms", "email"], recipients="invitee", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="invite.resent", variables=["chama_name", "inviter_name", "invite_link", "invite_code"]),
    _event("invite_accepted", category=NotificationCategory.INVITE, channels=["in_app", "email"], recipients="inviter_and_chama_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="invite.accepted", variables=["invitee_name", "chama_name"]),
    _event("invite_declined", category=NotificationCategory.INVITE, channels=["in_app", "email"], recipients="inviter_and_chama_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="invite.declined", variables=["invitee_name", "chama_name"]),
    _event("invite_expired", category=NotificationCategory.INVITE, channels=["in_app", "email"], recipients="inviter_and_chama_admins", schedule="scheduled", disableable=True, priority=NotificationPriority.LOW, source="invite.expired", variables=["invitee_identifier", "chama_name"]),
    _event("member_joined", category=NotificationCategory.MEMBERSHIP, channels=["in_app"], recipients="chama_admins_or_enabled_members", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="membership.created", variables=["member_name", "chama_name"]),
    _event("member_removed", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email", "sms"], recipients="removed_user_and_chama_admins", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="membership.removed", variables=["member_name", "chama_name", "reason"]),
    _event("membership_suspended", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email"], recipients="affected_user_and_chama_admins", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="membership.suspended", variables=["member_name", "reason", "chama_name"]),
    _event("membership_reinstated", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email"], recipients="affected_user_and_chama_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="membership.reinstated", variables=["member_name", "chama_name"]),
    _event("join_request_submitted", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email"], recipients="chama_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="membership.join_request_submitted", variables=["applicant_name", "chama_name"]),
    _event("join_request_reviewed", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email", "sms"], recipients="applicant", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="membership.join_request_reviewed", variables=["decision", "chama_name", "review_note"]),
    _event("role_changed", category=NotificationCategory.MEMBERSHIP, channels=["in_app", "email"], recipients="affected_user_and_chama_admins", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="membership.role_changed", variables=["previous_role", "new_role", "chama_name"]),
    _event("contribution_due_reminder", category=NotificationCategory.CONTRIBUTIONS, channels=["in_app", "sms", "email"], recipients="eligible_members", schedule="scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="finance.contribution_due", variables=["contribution_name", "amount", "due_date", "chama_name"]),
    _event("contribution_due_today", category=NotificationCategory.CONTRIBUTIONS, channels=["in_app", "sms"], recipients="eligible_members", schedule="scheduled", disableable=True, priority=NotificationPriority.HIGH, source="finance.contribution_due_today", variables=["contribution_name", "amount", "chama_name"]),
    _event("contribution_overdue", category=NotificationCategory.CONTRIBUTIONS, channels=["in_app", "sms", "email"], recipients="overdue_members", schedule="scheduled", disableable=True, priority=NotificationPriority.HIGH, source="finance.contribution_overdue", variables=["contribution_name", "amount", "days_overdue", "chama_name"]),
    _event("payment_initiated", category=NotificationCategory.PAYMENTS, channels=["in_app"], recipients="payer", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payments.initiated", variables=["amount", "payment_reference"]),
    _event("payment_pending", category=NotificationCategory.PAYMENTS, channels=["in_app"], recipients="payer", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payments.pending", variables=["amount", "payment_reference"]),
    _event("payment_success", category=NotificationCategory.PAYMENTS, channels=["in_app", "email", "sms"], recipients="payer_and_optional_finance_roles", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="payments.success", variables=["amount", "receipt_number", "payment_reference", "chama_name"]),
    _event("payment_failed", category=NotificationCategory.PAYMENTS, channels=["in_app", "sms", "email"], recipients="payer", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="payments.failed", variables=["amount", "failure_reason", "payment_reference"]),
    _event("payment_cancelled", category=NotificationCategory.PAYMENTS, channels=["in_app"], recipients="payer", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payments.cancelled", variables=["payment_reference"]),
    _event("receipt_available", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="payer", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payments.receipt_generated", variables=["receipt_number", "amount"]),
    _event("manual_cash_payment_recorded", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="payer_and_finance_roles", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payments.manual_recorded", variables=["amount", "recorded_by", "chama_name"]),
    _event("finance_approval_required", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="approvers", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="finance.approval_required", variables=["request_type", "amount", "chama_name"]),
    _event("expense_submitted", category=NotificationCategory.PAYMENTS, channels=["in_app"], recipients="approvers", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="finance.expense_submitted", variables=["amount", "requester_name", "expense_category"]),
    _event("expense_reviewed", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="requester_and_approvers", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="finance.expense_reviewed", variables=["decision", "amount", "review_note"]),
    _event("disbursement_initiated", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="approvers", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="finance.disbursement_initiated", variables=["amount", "request_type"]),
    _event("disbursement_reviewed", category=NotificationCategory.PAYMENTS, channels=["in_app", "email", "sms"], recipients="requester_and_relevant_users", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="finance.disbursement_reviewed", variables=["decision", "amount"]),
    _event("fine_issued", category=NotificationCategory.FINES, channels=["in_app", "email", "sms"], recipients="affected_member", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="finance.fine_issued", variables=["amount", "reason", "due_date"]),
    _event("fine_overdue", category=NotificationCategory.FINES, channels=["in_app", "sms"], recipients="affected_member", schedule="scheduled", disableable=True, priority=NotificationPriority.HIGH, source="finance.fine_overdue", variables=["amount", "days_overdue"]),
    _event("loan_application_submitted", category=NotificationCategory.LOANS, channels=["in_app", "email"], recipients="loan_approvers", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="finance.loan_application_submitted", variables=["applicant_name", "amount"]),
    _event("loan_reviewed", category=NotificationCategory.LOANS, channels=["in_app", "email", "sms"], recipients="loan_applicant", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="finance.loan_reviewed", variables=["decision", "amount", "review_note"]),
    _event("loan_repayment_due", category=NotificationCategory.LOANS, channels=["in_app", "sms", "email"], recipients="borrower", schedule="scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="finance.loan_repayment_due", variables=["amount", "due_date"]),
    _event("loan_repayment_overdue", category=NotificationCategory.LOANS, channels=["in_app", "sms", "email"], recipients="borrower", schedule="scheduled", disableable=True, priority=NotificationPriority.HIGH, source="finance.loan_repayment_overdue", variables=["amount", "days_overdue"]),
    _event("monthly_finance_summary_ready", category=NotificationCategory.PAYMENTS, channels=["in_app", "email"], recipients="finance_roles", schedule="scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="finance.monthly_summary_ready", variables=["period_label", "report_link", "chama_name"]),
    _event("meeting_created", category=NotificationCategory.MEETINGS, channels=["in_app", "email"], recipients="relevant_members", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="meetings.created", variables=["meeting_title", "meeting_date", "chama_name"]),
    _event("meeting_reminder_24h", category=NotificationCategory.MEETINGS, channels=["in_app", "sms", "email"], recipients="relevant_members", schedule="scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="meetings.reminder_24h", variables=["meeting_title", "meeting_date", "chama_name"]),
    _event("meeting_reminder_1h", category=NotificationCategory.MEETINGS, channels=["in_app", "sms"], recipients="relevant_members", schedule="scheduled", disableable=True, priority=NotificationPriority.HIGH, source="meetings.reminder_1h", variables=["meeting_title", "meeting_date", "meeting_link"]),
    _event("meeting_updated", category=NotificationCategory.MEETINGS, channels=["in_app", "email", "sms"], recipients="relevant_members", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="meetings.updated", variables=["meeting_title", "meeting_date", "change_summary"]),
    _event("meeting_cancelled", category=NotificationCategory.MEETINGS, channels=["in_app", "email", "sms"], recipients="relevant_members", schedule="immediate", disableable=False, priority=NotificationPriority.CRITICAL, source="meetings.cancelled", variables=["meeting_title", "meeting_date", "cancellation_reason"]),
    _event("agenda_published", category=NotificationCategory.MEETINGS, channels=["in_app"], recipients="relevant_members", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="meetings.agenda_published", variables=["meeting_title"]),
    _event("minutes_published", category=NotificationCategory.MEETINGS, channels=["in_app", "email"], recipients="relevant_members", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="meetings.minutes_published", variables=["meeting_title", "minutes_link"]),
    _event("resolution_passed", category=NotificationCategory.GOVERNANCE, channels=["in_app", "email"], recipients="relevant_members", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="meetings.resolution_passed", variables=["resolution_text", "meeting_title"]),
    _event("attendance_marked", category=NotificationCategory.MEETINGS, channels=["in_app"], recipients="affected_member", schedule="immediate", disableable=True, priority=NotificationPriority.LOW, source="meetings.attendance_marked", variables=["meeting_title", "attendance_status"]),
    _event("announcement_posted", category=NotificationCategory.SYSTEM, channels=["in_app", "email", "sms"], recipients="selected_members", schedule="immediate_or_scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="announcements.published", variables=["title", "message", "chama_name"]),
    _event("urgent_announcement", category=NotificationCategory.SYSTEM, channels=["in_app", "sms", "email"], recipients="selected_members", schedule="immediate", disableable=False, priority=NotificationPriority.CRITICAL, source="announcements.urgent", variables=["title", "message", "chama_name"]),
    _event("announcement_edited", category=NotificationCategory.SYSTEM, channels=["in_app"], recipients="selected_members", schedule="immediate", disableable=True, priority=NotificationPriority.LOW, source="announcements.edited", variables=["title", "change_summary"]),
    _event("admin_broadcast", category=NotificationCategory.SYSTEM, channels=["in_app", "email", "sms"], recipients="selected_segment", schedule="immediate_or_scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="admin.broadcast_created", variables=["title", "message", "action_url"]),
    _event("support_ticket_reply", category=NotificationCategory.SYSTEM, channels=["in_app", "email"], recipients="ticket_owner", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="support.reply_created", variables=["ticket_reference", "reply_excerpt"]),
    _event("maintenance_notice", category=NotificationCategory.SYSTEM, channels=["in_app", "email", "sms"], recipients="selected_segment", schedule="immediate_or_scheduled", disableable=False, priority=NotificationPriority.CRITICAL, source="system.maintenance_notice", variables=["window_start", "window_end", "status_page_url"]),
    _event("policy_update", category=NotificationCategory.SECURITY, channels=["in_app", "email"], recipients="all_active_users", schedule="immediate_or_scheduled", disableable=False, priority=NotificationPriority.HIGH, source="system.policy_updated", variables=["policy_name", "effective_date"]),
    _event("report_ready", category=NotificationCategory.SYSTEM, channels=["in_app", "email"], recipients="requesting_user", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="reports.generated", variables=["report_name", "download_url"]),
    _event("ai_insight_ready", category=NotificationCategory.SYSTEM, channels=["in_app"], recipients="authorized_requester", schedule="immediate", disableable=True, priority=NotificationPriority.LOW, source="ai.insight_ready", variables=["insight_type", "result_id"]),
    # Payout notifications
    _event("payout_triggered", category=NotificationCategory.PAYMENTS, channels=["in_app", "push"], recipients="treasurer_and_admin", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="payouts.payout_triggered", variables=["member_name", "payout_amount", "chama_name"]),
    _event("payout_awaiting_review", category=NotificationCategory.PAYMENTS, channels=["in_app", "push"], recipients="treasurer", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="payouts.eligibility_checked", variables=["member_name", "payout_amount", "chama_name"]),
    _event("payout_awaiting_chair_approval", category=NotificationCategory.PAYMENTS, channels=["in_app", "push"], recipients="chairperson", schedule="immediate", disableable=False, priority=NotificationPriority.HIGH, source="payouts.treasurer_approved", variables=["member_name", "payout_amount", "chama_name"]),
    _event("payout_approved", category=NotificationCategory.PAYMENTS, channels=["in_app", "push", "email"], recipients="treasurer_and_chairperson", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payouts.approved", variables=["member_name", "payout_amount", "chama_name"]),
    _event("payout_rejected", category=NotificationCategory.PAYMENTS, channels=["in_app", "push", "sms"], recipients="member_and_admins", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="payouts.rejected", variables=["member_name", "chama_name", "reason"]),
    _event("payout_success", category=NotificationCategory.PAYMENTS, channels=["in_app", "push", "sms"], recipients="member", schedule="immediate", disableable=True, priority=NotificationPriority.HIGH, source="payouts.payment_success", variables=["payout_amount", "member_phone", "chama_name", "payment_method"]),
    _event("payout_failed", category=NotificationCategory.PAYMENTS, channels=["in_app", "push", "email"], recipients="treasurer_and_chairperson", schedule="immediate", disableable=False, priority=NotificationPriority.CRITICAL, source="payouts.payment_failed", variables=["member_name", "payout_amount", "failure_reason", "chama_name"]),
    _event("payout_on_hold", category=NotificationCategory.PAYMENTS, channels=["in_app", "push"], recipients="member_and_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payouts.flagged_on_hold", variables=["member_name", "chama_name", "hold_reason"]),
    _event("payout_hold_released", category=NotificationCategory.PAYMENTS, channels=["in_app", "push"], recipients="member_and_admins", schedule="immediate", disableable=True, priority=NotificationPriority.NORMAL, source="payouts.released_from_hold", variables=["member_name", "chama_name"]),
    _event("contribution_reminder", category=NotificationCategory.PAYMENTS, channels=["in_app", "push", "sms"], recipients="chama_members", schedule="scheduled", disableable=True, priority=NotificationPriority.NORMAL, source="payouts.contribution_reminder", variables=["chama_name", "rotation_position"]),
]


EVENT_CATALOG_BY_NAME = {
    item["event_name"]: item for item in NOTIFICATION_EVENT_CATALOG
}
