# Generated by Django 6.0.4 on 2026-04-26 00:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_add_audit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_chama_i_955f30_idx',
            old_name='payouts_payo_chama_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_member__536b4c_idx',
            old_name='payouts_payo_member_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_status_dd1f82_idx',
            old_name='payouts_payo_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_rotatio_faebcb_idx',
            old_name='payouts_payo_rotation_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutauditlog',
            new_name='payouts_pay_payout__f7bf4c_idx',
            old_name='payouts_payo_payout_action_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutauditlog',
            new_name='payouts_pay_created_8d9e4e_idx',
            old_name='payouts_payo_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payouteligibilitycheck',
            new_name='payouts_pay_member__4d6137_idx',
            old_name='payouts_payo_member_result_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrotation',
            new_name='payouts_pay_chama_i_c573c3_idx',
            old_name='payouts_payo_chama_idx',
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payoutauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payoutauditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payouteligibilitycheck',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payouteligibilitycheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payouteligibilitycheck',
            name='overdue_loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payouteligibilitycheck',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payouteligibilitycheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payoutrotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payoutrotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
