from django.urls import path

from apps.issues.views import (
    IssueAppealCreateView,
    IssueAppealListView,
    IssueAppealReviewView,
    IssueAssignView,
    IssueChairpersonApproveView,
    IssueChairpersonRejectView,
    IssueClarificationRequestView,
    IssueClarificationResponseView,
    IssueCloseView,
    IssueCommentCreateView,
    IssueDetailView,
    IssueDismissView,
    IssueEscalateView,
    IssueEscalationLadderView,
    IssueEvidenceCreateView,
    IssueExportView,
    IssueInvestigationUpdateView,
    IssueLiftSuspensionView,
    IssueListCreateView,
    IssueMediationNoteListCreateView,
    IssueProposeResolutionView,
    IssueRateView,
    IssueReopenView,
    IssueStartInvestigationView,
    IssueStatsView,
    IssueStatusUpdateView,
    IssueSuspendView,
    IssueWarnView,
    SystemIssueCreateView,
    IssueApproveResolutionView,
    IssueRejectResolutionView,
)

app_name = "issues"

urlpatterns = [
    path("", IssueListCreateView.as_view(), name="issue-list-create"),
    path("appeals", IssueAppealListView.as_view(), name="issue-appeal-list"),
    path("stats", IssueStatsView.as_view(), name="issue-stats"),
    path("export", IssueExportView.as_view(), name="issue-export"),
    path("system-create", SystemIssueCreateView.as_view(), name="system-issue-create"),
    path("<uuid:id>/", IssueDetailView.as_view(), name="issue-detail"),
    path("<uuid:id>/comments", IssueCommentCreateView.as_view(), name="issue-comment"),
    path(
        "<uuid:id>/evidences",
        IssueEvidenceCreateView.as_view(),
        name="issue-evidence",
    ),
    path("<uuid:id>/assign", IssueAssignView.as_view(), name="issue-assign"),
    path("<uuid:id>/status", IssueStatusUpdateView.as_view(), name="issue-status"),
    path("<uuid:id>/close", IssueCloseView.as_view(), name="issue-close"),
    path("<uuid:id>/reopen", IssueReopenView.as_view(), name="issue-reopen"),
    path("<uuid:id>/rate", IssueRateView.as_view(), name="issue-rate"),
    path("<uuid:id>/warn", IssueWarnView.as_view(), name="issue-warn"),
    path("<uuid:id>/suspend", IssueSuspendView.as_view(), name="issue-suspend"),
    path(
        "<uuid:id>/mediation-notes",
        IssueMediationNoteListCreateView.as_view(),
        name="issue-mediation-notes",
    ),
    path("<uuid:id>/escalate", IssueEscalateView.as_view(), name="issue-escalate"),
    path(
        "<uuid:id>/escalation-ladder",
        IssueEscalationLadderView.as_view(),
        name="issue-escalation-ladder",
    ),
    path("<uuid:id>/appeal", IssueAppealCreateView.as_view(), name="issue-appeal"),
    path(
        "appeals/<uuid:appeal_id>/review",
        IssueAppealReviewView.as_view(),
        name="issue-appeal-review",
    ),
    path(
        "<uuid:id>/lift-suspension",
        IssueLiftSuspensionView.as_view(),
        name="issue-lift-suspension",
    ),
    path(
        "<uuid:id>/clarification",
        IssueClarificationRequestView.as_view(),
        name="issue-clarification",
    ),
    path(
        "<uuid:id>/clarification-response",
        IssueClarificationResponseView.as_view(),
        name="issue-clarification-response",
    ),
    path(
        "<uuid:id>/investigation",
        IssueStartInvestigationView.as_view(),
        name="issue-investigation",
    ),
    path(
        "<uuid:id>/investigation-update",
        IssueInvestigationUpdateView.as_view(),
        name="issue-investigation-update",
    ),
    path(
        "<uuid:id>/resolution",
        IssueProposeResolutionView.as_view(),
        name="issue-resolution",
    ),
    path(
        "<uuid:id>/resolution/approve",
        IssueApproveResolutionView.as_view(),
        name="issue-resolution-approve",
    ),
    path(
        "<uuid:id>/resolution/reject",
        IssueRejectResolutionView.as_view(),
        name="issue-resolution-reject",
    ),
    path(
        "<uuid:id>/chairperson-approve",
        IssueChairpersonApproveView.as_view(),
        name="issue-chairperson-approve",
    ),
    path(
        "<uuid:id>/chairperson-reject",
        IssueChairpersonRejectView.as_view(),
        name="issue-chairperson-reject",
    ),
    path(
        "<uuid:id>/dismiss",
        IssueDismissView.as_view(),
        name="issue-dismiss",
    ),
]
