from django.urls import path

from apps.finance.views import (
    AllTransactionsView,
    ChamaLoanPolicyView,
    ContributionGoalDetailView,
    ContributionGoalListCreateView,
    ContributionDetailView,
    ContributionListView,
    ContributionRecordView,
    ContributionTypeDetailView,
    ContributionTypeListCreateView,
    CreditScoreView,
    DashboardView,
    ExpenseApproveView,
    ExpenseCategoryListCreateView,
    ExpenseListCreateView,
    ExpenseMarkPaidView,
    ExpenseRejectView,
    FinanceReportsView,
    FinanceSummaryView,
    FinancialSnapshotListView,
    LedgerReverseView,
    LedgerView,
    LoanApplicationApprovalLogListView,
    LoanApplicationApproveView,
    LoanApplicationCommitteeApproveView,
    LoanApplicationDisburseView,
    LoanApplicationGuarantorListCreateView,
    LoanApplicationGuarantorRespondView,
    LoanApplicationListCreateView,
    LoanApplicationRejectView,
    LoanApplicationReviewView,
    LoanApprovalLogListView,
    LoanApproveView,
    LoanDisburseView,
    LoanEligibilityView,
    LoanGuarantorListCreateView,
    LoanGuarantorRespondView,
    LoanListView,
    LoanNextDueView,
    LoanOffsetFromSavingsView,
    LoanPolicyDetailView,
    LoanPolicyListCreateView,
    LoanPortfolioView,
    LoanRecoveryActionListCreateView,
    LoanRejectView,
    LoanRepayView,
    LoanReportsView,
    LoanRequestView,
    LoanRestructureRequestView,
    LoanRestructureRequestListView,
    LoanRestructureReviewView,
    LoanReviewView,
    LoanScheduleView,
    LoanTopUpRequestView,
    LoanTopUpReviewView,
    LoanWriteOffView,
    ManualAdjustmentView,
    MemberContributionSummaryView,
    MemberPenaltyListView,
    MemberContributionWorkspaceView,
    MemberWalletDepositDetailView,
    MemberWalletDepositView,
    MemberLoanWorkspaceView,
    MemberWalletActivityView,
    MemberWalletContributionView,
    MemberWalletTransferView,
    MemberWalletTransactionDetailView,
    MemberWalletWithdrawalDetailView,
    MemberWalletWithdrawalView,
    MemberWalletWorkspaceView,
    FastMobileDashboardSummary,
    MonthCloseListView,
    MonthCloseView,
    MonthlyAggregatesView,
    PenaltyIssueView,
    PenaltyMarkPaidView,
    PenaltyWaiveView,
    TransactionDetailView,
    StatementView,
    WalletBalanceView,
    WalletSummaryView,
)

app_name = "finance"

urlpatterns = [
    path(
        "loan-governance-policy/",
        ChamaLoanPolicyView.as_view(),
        name="loan-governance-policy",
    ),
    path(
        "loan-policies/",
        LoanPolicyListCreateView.as_view(),
        name="loan-policy-list",
    ),
    path(
        "loan-policies/<uuid:id>/",
        LoanPolicyDetailView.as_view(),
        name="loan-policy-detail",
    ),
    path(
        "contribution-types/",
        ContributionTypeListCreateView.as_view(),
        name="contribution-type-list",
    ),
    path(
        "contribution-types/<uuid:id>/",
        ContributionTypeDetailView.as_view(),
        name="contribution-type-detail",
    ),
    path(
        "contributions/",
        ContributionListView.as_view(),
        name="contribution-list",
    ),
    path(
        "contributions/<uuid:id>/",
        ContributionDetailView.as_view(),
        name="contribution-detail",
    ),
    path(
        "contributions/record",
        ContributionRecordView.as_view(),
        name="contribution-record",
    ),
    path("contribution-goals/", ContributionGoalListCreateView.as_view(), name="contribution-goals"),
    path(
        "contribution-goals/<uuid:id>/",
        ContributionGoalDetailView.as_view(),
        name="contribution-goal-detail",
    ),
    path("wallet", WalletBalanceView.as_view(), name="wallet-balance"),
    path("wallet/summary", WalletSummaryView.as_view(), name="wallet-summary"),
    path("member-wallet/workspace", MemberWalletWorkspaceView.as_view(), name="member-wallet-workspace"),
    path("mobile/dashboard", FastMobileDashboardSummary.as_view(), name="fast-mobile-dashboard"),
    path("member-wallet/activity", MemberWalletActivityView.as_view(), name="member-wallet-activity"),
    path("member-wallet/deposits", MemberWalletDepositView.as_view(), name="member-wallet-deposit"),
    path("member-wallet/contributions", MemberWalletContributionView.as_view(), name="member-wallet-contribution"),
    path("member-wallet/transfers", MemberWalletTransferView.as_view(), name="member-wallet-transfer"),
    path(
        "member-wallet/deposits/<uuid:intent_id>",
        MemberWalletDepositDetailView.as_view(),
        name="member-wallet-deposit-detail",
    ),
    path(
        "member-wallet/withdrawals",
        MemberWalletWithdrawalView.as_view(),
        name="member-wallet-withdrawal",
    ),
    path(
        "member-wallet/withdrawals/<uuid:intent_id>",
        MemberWalletWithdrawalDetailView.as_view(),
        name="member-wallet-withdrawal-detail",
    ),
    path(
        "member-wallet/transactions/<str:transaction_ref>",
        MemberWalletTransactionDetailView.as_view(),
        name="member-wallet-transaction-detail",
    ),
    path("credit-score", CreditScoreView.as_view(), name="credit-score"),
    path("loans/", LoanListView.as_view(), name="loan-list"),
    path(
        "loan-applications/",
        LoanApplicationListCreateView.as_view(),
        name="loan-application-list-create",
    ),
    path("loans/eligibility", LoanEligibilityView.as_view(), name="loan-eligibility"),
    path("loans/request", LoanRequestView.as_view(), name="loan-request"),
    path(
        "loan-applications/<uuid:id>/review",
        LoanApplicationReviewView.as_view(),
        name="loan-application-review",
    ),
    path(
        "loan-applications/<uuid:id>/guarantors",
        LoanApplicationGuarantorListCreateView.as_view(),
        name="loan-application-guarantors",
    ),
    path(
        "loan-applications/<uuid:id>/committee-approve",
        LoanApplicationCommitteeApproveView.as_view(),
        name="loan-application-committee-approve",
    ),
    path(
        "loan-applications/<uuid:id>/approve",
        LoanApplicationApproveView.as_view(),
        name="loan-application-approve",
    ),
    path(
        "loan-applications/<uuid:id>/reject",
        LoanApplicationRejectView.as_view(),
        name="loan-application-reject",
    ),
    path(
        "loan-applications/<uuid:id>/disburse",
        LoanApplicationDisburseView.as_view(),
        name="loan-application-disburse",
    ),
    path(
        "loan-applications/<uuid:id>/approvals",
        LoanApplicationApprovalLogListView.as_view(),
        name="loan-application-approvals",
    ),
    path(
        "loan-application-guarantors/<uuid:id>/respond",
        LoanApplicationGuarantorRespondView.as_view(),
        name="loan-application-guarantor-respond",
    ),
    path(
        "loans/<uuid:id>/guarantors",
        LoanGuarantorListCreateView.as_view(),
        name="loan-guarantors",
    ),
    path(
        "loan-guarantors/<uuid:id>/respond",
        LoanGuarantorRespondView.as_view(),
        name="loan-guarantor-respond",
    ),
    path("loans/<uuid:id>/review", LoanReviewView.as_view(), name="loan-review"),
    path("loans/<uuid:id>/approve", LoanApproveView.as_view(), name="loan-approve"),
    path("loans/<uuid:id>/reject", LoanRejectView.as_view(), name="loan-reject"),
    path("loans/<uuid:id>/disburse", LoanDisburseView.as_view(), name="loan-disburse"),
    path("loans/<uuid:id>/repay", LoanRepayView.as_view(), name="loan-repay"),
    path(
        "loans/<uuid:id>/recovery-actions",
        LoanRecoveryActionListCreateView.as_view(),
        name="loan-recovery-actions",
    ),
    path(
        "loans/<uuid:id>/offset",
        LoanOffsetFromSavingsView.as_view(),
        name="loan-offset",
    ),
    path(
        "loans/<uuid:id>/write-off",
        LoanWriteOffView.as_view(),
        name="loan-write-off",
    ),
    path("loans/<uuid:id>/topup/request", LoanTopUpRequestView.as_view(), name="loan-topup-request"),
    path("loans/topups/<uuid:id>/review", LoanTopUpReviewView.as_view(), name="loan-topup-review"),
    path(
        "loans/restructures/",
        LoanRestructureRequestListView.as_view(),
        name="loan-restructure-list",
    ),
    path(
        "loans/<uuid:id>/restructure/request",
        LoanRestructureRequestView.as_view(),
        name="loan-restructure-request",
    ),
    path(
        "loans/restructures/<uuid:id>/review",
        LoanRestructureReviewView.as_view(),
        name="loan-restructure-review",
    ),
    path("loans/<uuid:id>/schedule", LoanScheduleView.as_view(), name="loan-schedule"),
    path("loans/<uuid:id>/next-due", LoanNextDueView.as_view(), name="loan-next-due"),
    path(
        "loans/<uuid:id>/approvals",
        LoanApprovalLogListView.as_view(),
        name="loan-approvals",
    ),
    path("loans/reports", LoanReportsView.as_view(), name="loan-reports-list"),
    path(
        "expense-categories/",
        ExpenseCategoryListCreateView.as_view(),
        name="expense-category-list-create",
    ),
    path("penalties/issue", PenaltyIssueView.as_view(), name="penalty-issue"),
    path(
        "penalties/<uuid:id>/mark-paid",
        PenaltyMarkPaidView.as_view(),
        name="penalty-mark-paid",
    ),
    path("penalties/<uuid:id>/waive", PenaltyWaiveView.as_view(), name="penalty-waive"),
    path("ledger", LedgerView.as_view(), name="ledger"),
    path("transactions", AllTransactionsView.as_view(), name="all-transactions"),
    path(
        "transactions/<str:transaction_ref>",
        TransactionDetailView.as_view(),
        name="transaction-detail",
    ),
    path("summary", FinanceSummaryView.as_view(), name="finance-summary"),
    path("reports", FinanceReportsView.as_view(), name="finance-reports"),
    path(
        "member-contributions",
        MemberContributionSummaryView.as_view(),
        name="finance-member-contributions",
    ),
    path(
        "member-contributions/workspace",
        MemberContributionWorkspaceView.as_view(),
        name="finance-member-contribution-workspace",
    ),
    path(
        "member-contributions/penalties",
        MemberPenaltyListView.as_view(),
        name="finance-member-contribution-penalties",
    ),
    path(
        "member-loans/workspace",
        MemberLoanWorkspaceView.as_view(),
        name="finance-member-loan-workspace",
    ),
    path("expenses/", ExpenseListCreateView.as_view(), name="expense-list-create"),
    path("expenses/<uuid:id>/approve", ExpenseApproveView.as_view(), name="expense-approve"),
    path("expenses/<uuid:id>/reject", ExpenseRejectView.as_view(), name="expense-reject"),
    path("expenses/<uuid:id>/mark-paid", ExpenseMarkPaidView.as_view(), name="expense-mark-paid"),
    path("snapshots", FinancialSnapshotListView.as_view(), name="financial-snapshots"),
    path(
        "ledger/<uuid:id>/reverse", LedgerReverseView.as_view(), name="ledger-reverse"
    ),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("loan-portfolio", LoanPortfolioView.as_view(), name="loan-portfolio"),
    path("statement", StatementView.as_view(), name="statement"),
    path(
        "monthly-aggregates", MonthlyAggregatesView.as_view(), name="monthly-aggregates"
    ),
    path(
        "adjustments/manual", ManualAdjustmentView.as_view(), name="manual-adjustment"
    ),
    path("month-close", MonthCloseView.as_view(), name="month-close"),
    path("month-close/list", MonthCloseListView.as_view(), name="month-close-list"),
]
