# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone", models.CharField(max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("contribution", "Contribution"),
                            ("repayment", "Loan Repayment"),
                            ("penalty", "Penalty Payment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "checkout_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("merchant_request_id", models.CharField(blank=True, max_length=100)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending_callback", "Pending Callback"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("callback_received_at", models.DateTimeField(blank=True, null=True)),
                ("raw_callback", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_mpesa_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpesa_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaCallbackLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("merchant_request_id", models.CharField(blank=True, max_length=100)),
                ("checkout_request_id", models.CharField(blank=True, max_length=100)),
                ("callback_data", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_logs",
                        to="payments.mpesatransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("repayment_first", "Repayment First"),
                            ("welfare_first", "Welfare First"),
                            ("ratio", "Ratio Split"),
                        ],
                        default="repayment_first",
                        max_length=32,
                    ),
                ),
                (
                    "repayment_ratio_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chama",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocation_rule",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "welfare_contribution_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_rules",
                        to="finance.contributiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "intent_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("LOAN_REPAYMENT", "Loan Repayment"),
                            ("LOAN_DISBURSEMENT", "Loan Disbursement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CONTRIBUTION", "Contribution"),
                            ("LOAN_REPAYMENT", "Loan Repayment"),
                            ("SPLIT_ALLOCATION", "Split Allocation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="KES",
                        max_length=3,
                    ),
                ),
                ("phone", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate Charge"),
                            ("incorrect_amount", "Incorrect Amount"),
                            ("failed_callback", "Failed Callback"),
                            ("missing_reference", "Missing Reference"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_disputes",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STK_SENT", "STK Sent"),
                            ("C2B_VALIDATED", "C2B Validation"),
                            ("C2B_CONFIRMED", "C2B Confirmation"),
                            ("B2C_REQUESTED", "B2C Requested"),
                            ("CALLBACK_RECEIVED", "Callback Received"),
                            ("POSTED_TO_LEDGER", "Posted To Ledger"),
                            (
                                "LOAN_DISBURSEMENT_REQUESTED",
                                "Loan Disbursement Requested",
                            ),
                            ("LOAN_DISBURSED", "Loan Disbursed"),
                            ("LOAN_REPAYMENT_POSTED", "Loan Repayment Posted"),
                            ("REFUND_REQUESTED", "Refund Requested"),
                            ("REFUND_APPROVED", "Refund Approved"),
                            ("REFUND_REJECTED", "Refund Rejected"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("DISPUTE_OPENED", "Dispute Opened"),
                            ("DISPUTE_RESOLVED", "Dispute Resolved"),
                            ("NOTIFIED", "Notified"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaSTKTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone", models.CharField(max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("merchant_request_id", models.CharField(blank=True, max_length=120)),
                ("checkout_request_id", models.CharField(max_length=120, unique=True)),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("result_desc", models.TextField(blank=True)),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("raw_callback", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_stk_transactions",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stk_transactions",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaC2BTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone", models.CharField(max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("PayBill", "PayBill"), ("BuyGoods", "BuyGoods")],
                        default="PayBill",
                        max_length=20,
                    ),
                ),
                ("trans_id", models.CharField(max_length=80, unique=True)),
                ("bill_ref_number", models.CharField(blank=True, max_length=100)),
                ("account_reference", models.CharField(blank=True, max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("middle_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60)),
                ("trans_time", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("POSTED", "Posted"),
                            ("DUPLICATE", "Duplicate"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_c2b_transactions",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="c2b_transactions",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-trans_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaB2CPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone", models.CharField(max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "command_id",
                    models.CharField(default="BusinessPayment", max_length=50),
                ),
                ("remarks", models.TextField(blank=True)),
                ("occasion", models.CharField(blank=True, max_length=120)),
                (
                    "originator_conversation_id",
                    models.CharField(max_length=120, unique=True),
                ),
                ("conversation_id", models.CharField(blank=True, max_length=120)),
                ("response_code", models.CharField(blank=True, max_length=20)),
                ("response_description", models.TextField(blank=True)),
                ("result_code", models.CharField(blank=True, max_length=20)),
                ("result_desc", models.TextField(blank=True)),
                ("transaction_id", models.CharField(blank=True, max_length=80)),
                ("receipt_number", models.CharField(blank=True, max_length=80)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_b2c_payouts",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2c_payouts",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("run_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("anomalies", models.JSONField(blank=True, default=dict)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_reconciliation_runs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-run_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payment_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_refunds",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_reversal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_refunds",
                        to="finance.ledgerentry",
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payment_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_payment_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UssdSessionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("session_id", models.CharField(db_index=True, max_length=120)),
                ("phone", models.CharField(db_index=True, max_length=16)),
                ("service_code", models.CharField(blank=True, max_length=40)),
                ("text", models.TextField(blank=True)),
                ("response_text", models.TextField(blank=True)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ussd_session_logs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ussd_session_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalApprovalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("TREASURER_APPROVED", "Treasurer Approved"),
                            ("ADMIN_APPROVED", "Admin Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_approval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_approval_logs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallbackLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "callback_type",
                    models.CharField(
                        choices=[
                            ("c2b_validation", "C2B Validation"),
                            ("c2b_confirmation", "C2B Confirmation"),
                            ("stk", "STK Callback"),
                            ("b2c_result", "B2C Result"),
                            ("b2c_timeout", "B2C Timeout"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["callback_type", "created_at"],
                        name="payments_ca_callbac_276a94_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "created_at"],
                        name="payments_ca_source__7312ee_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["chama", "status"], name="payments_mp_chama_i_f69065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["purpose", "status"], name="payments_mp_purpose_2e59ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["checkout_request_id"], name="payments_mp_checkou_a6f836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["receipt_number"], name="payments_mp_receipt_46c6d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesatransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number", ""), _negated=True),
                fields=("chama", "receipt_number"),
                name="uniq_mpesa_receipt_per_chama",
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesatransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="legacy_mpesa_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesacallbacklog",
            index=models.Index(
                fields=["transaction", "created_at"],
                name="payments_mp_transac_c83c3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesacallbacklog",
            index=models.Index(
                fields=["checkout_request_id"], name="payments_mp_checkou_bd027d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocationrule",
            index=models.Index(
                fields=["strategy", "is_active"], name="payments_pa_strateg_9cc301_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repayment_ratio_percent__gte", Decimal("0.00")),
                    ("repayment_ratio_percent__lte", Decimal("100.00")),
                ),
                name="payment_allocation_ratio_between_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["chama", "status", "intent_type"],
                name="payments_pa_chama_i_09af0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="payments_pa_referen_dd729b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="payments_pa_created_b22a4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["phone", "created_at"], name="payments_pa_phone_9e213a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                fields=("chama", "idempotency_key"),
                name="uniq_payment_intent_idempotency_per_chama",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="payment_intent_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["chama", "status", "created_at"],
                name="payments_pa_chama_i_397c70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["opened_by", "status", "created_at"],
                name="payments_pa_opened__a156e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["payment_intent", "status", "created_at"],
                name="payments_pa_payment_e8a1ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentactivitylog",
            index=models.Index(
                fields=["payment_intent", "created_at"],
                name="payments_pa_payment_dc93a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentactivitylog",
            index=models.Index(
                fields=["event", "created_at"], name="payments_pa_event_236095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesastktransaction",
            index=models.Index(
                fields=["chama", "status", "created_at"],
                name="payments_mp_chama_i_956e1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesastktransaction",
            index=models.Index(
                fields=["merchant_request_id"], name="payments_mp_merchan_e665cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesastktransaction",
            index=models.Index(
                fields=["mpesa_receipt_number"], name="payments_mp_mpesa_r_f6cf3b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesastktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="mpesa_stk_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesastktransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("mpesa_receipt_number__isnull", False),
                    models.Q(("mpesa_receipt_number", ""), _negated=True),
                ),
                fields=("chama", "mpesa_receipt_number"),
                name="uniq_mpesa_stk_receipt_per_chama",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesac2btransaction",
            index=models.Index(
                fields=["chama", "processing_status", "created_at"],
                name="payments_mp_chama_i_807a2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesac2btransaction",
            index=models.Index(
                fields=["account_reference"], name="payments_mp_account_d0ee20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesac2btransaction",
            index=models.Index(
                fields=["bill_ref_number"], name="payments_mp_bill_re_d37fe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesac2btransaction",
            index=models.Index(
                fields=["phone", "trans_time"], name="payments_mp_phone_f94bc2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesac2btransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="mpesa_c2b_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesab2cpayout",
            index=models.Index(
                fields=["chama", "status", "created_at"],
                name="payments_mp_chama_i_6017f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mpesab2cpayout",
            index=models.Index(
                fields=["conversation_id"], name="payments_mp_convers_ecc9be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesab2cpayout",
            index=models.Index(
                fields=["transaction_id"], name="payments_mp_transac_c93afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesab2cpayout",
            index=models.Index(
                fields=["receipt_number"], name="payments_mp_receipt_7bae25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesab2cpayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="mpesa_b2c_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationrun",
            index=models.Index(
                fields=["chama", "run_at"], name="payments_pa_chama_i_b2455c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationrun",
            index=models.Index(
                fields=["status", "run_at"], name="payments_pa_status_7b4012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["chama", "status", "created_at"],
                name="payments_pa_chama_i_99dcc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["payment_intent", "status", "created_at"],
                name="payments_pa_payment_8b50f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="payments_pa_request_03b0e7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.UniqueConstraint(
                fields=("chama", "idempotency_key"),
                name="uniq_payment_refund_idempotency_per_chama",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="payment_refund_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="ussdsessionlog",
            index=models.Index(
                fields=["session_id", "created_at"],
                name="payments_us_session_43ce94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ussdsessionlog",
            index=models.Index(
                fields=["phone", "created_at"], name="payments_us_phone_3d77b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ussdsessionlog",
            index=models.Index(
                fields=["processed", "created_at"],
                name="payments_us_process_f20fe9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalapprovallog",
            index=models.Index(
                fields=["payment_intent", "created_at"],
                name="payments_wi_payment_c5d707_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalapprovallog",
            index=models.Index(
                fields=["chama", "step", "created_at"],
                name="payments_wi_chama_i_3d2169_idx",
            ),
        ),
    ]
