# Generated by Django 5.1.6 on 2026-03-31 19:57

import apps.payments.unified_models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0006_rename_chama_contr_contrib_b3165c_idx_chama_chama_contrib_f4ff8c_idx_and_more'),
        ('finance', '0009_rename_finance_acc_chama_t_0f4bdc_idx_finance_acc_chama_i_d802fa_idx_and_more'),
        ('payments', '0007_payment_dispute_chargeback_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider_intent_id', models.CharField(help_text="Provider's payment intent ID", max_length=255, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_country', models.CharField(blank=True, max_length=2)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPaymentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone', models.CharField(help_text='M-Pesa phone number', max_length=16)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider', models.CharField(help_text='Provider name (stripe, flutterwave, safaricom, etc.)', max_length=50)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentreconciliationcase',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_cases', to='payments.paymentwebhook'),
        ),
        migrations.RemoveIndex(
            model_name='paymentintent',
            name='payments_pa_chama_i_09af0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentintent',
            name='payments_pa_referen_dd729b_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentintent',
            name='payments_pa_created_b22a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentintent',
            name='payments_pa_phone_9e213a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_provide_8094be_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpaymentdetails',
            new_name='payments_ba_bank_na_45631a_idx',
            old_name='payments_bank_name_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpaymentdetails',
            new_name='payments_ba_transfe_e0d100_idx',
            old_name='payments_bank_transfer_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentauditlog',
            new_name='payments_ca_payment_610e98_idx',
            old_name='payments_cpal_intent_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentauditlog',
            new_name='payments_ca_event_bd94b3_idx',
            old_name='payments_cpal_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentauditlog',
            new_name='payments_ca_actor_i_419e48_idx',
            old_name='payments_cpal_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_chama_i_6e8030_idx',
            old_name='payments_cpi_chama_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_user_id_7339b4_idx',
            old_name='payments_cpi_user_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_provide_f303c8_idx',
            old_name='payments_cpi_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_provide_b8587d_idx',
            old_name='payments_cpi_provider_intent_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_contrib_809a63_idx',
            old_name='payments_cpi_contribution_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentintent',
            new_name='payments_ca_contrib_2be9c5_idx',
            old_name='payments_cpi_contribution_type_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentreceipt',
            new_name='payments_ca_referen_026c90_idx',
            old_name='payments_cpr_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentreceipt',
            new_name='payments_ca_receipt_1abf38_idx',
            old_name='payments_cpr_receipt_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentreceipt',
            new_name='payments_ca_issued__1a3551_idx',
            old_name='payments_cpr_issued_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymenttransaction',
            new_name='payments_ca_payment_17adc7_idx',
            old_name='payments_cpt_intent_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymenttransaction',
            new_name='payments_ca_provide_266cf8_idx',
            old_name='payments_cpt_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymenttransaction',
            new_name='payments_ca_provide_db6da2_idx',
            old_name='payments_cpt_provider_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymenttransaction',
            new_name='payments_ca_card_br_554564_idx',
            old_name='payments_cpt_card_mask_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentwebhook',
            new_name='payments_ca_provide_f98989_idx',
            old_name='payments_cpw_provider_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentwebhook',
            new_name='payments_ca_provide_1c64c6_idx',
            old_name='payments_cpw_provider_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpaymentwebhook',
            new_name='payments_ca_process_9264e8_idx',
            old_name='payments_cpw_processed_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cashpaymentdetails',
            new_name='payments_ca_receive_227423_idx',
            old_name='payments_cash_received_idx',
        ),
        migrations.RenameIndex(
            model_name='cashpaymentdetails',
            new_name='payments_ca_receipt_214c87_idx',
            old_name='payments_cash_receipt_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentdispute',
            new_name='payments_pa_provide_3675f6_idx',
            old_name='payments_pay_provider_bf43c7_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliationcase',
            new_name='payments_pa_chama_i_34ed31_idx',
            old_name='payments_prc_chama_status_type_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliationcase',
            new_name='payments_pa_payment_09bc55_idx',
            old_name='payments_prc_intent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliationcase',
            new_name='payments_pa_payment_4fae49_idx',
            old_name='payments_prc_tx_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreconciliationcase',
            new_name='payments_pa_assigne_58d235_idx',
            old_name='payments_prc_assignee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsettlement',
            new_name='payments_pa_chama_i_8c4a66_idx',
            old_name='payments_pay_chama_i_906f29_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsettlement',
            new_name='payments_pa_provide_3eb036_idx',
            old_name='payments_pay_provider_496567_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsettlement',
            new_name='payments_pa_settlem_44dd25_idx',
            old_name='payments_pay_settlem_5664b6_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsettlementallocation',
            new_name='payments_pa_settlem_5d02b8_idx',
            old_name='payments_pay_settlem_ef1725_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsettlementallocation',
            new_name='payments_pa_payment_b0f328_idx',
            old_name='payments_pay_payment_16d098_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentstatementimport',
            new_name='payments_pa_chama_i_925cfa_idx',
            old_name='payments_stmtimport_chama_method_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentstatementimport',
            new_name='payments_pa_status_ff648d_idx',
            old_name='payments_stmtimport_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentstatementline',
            new_name='payments_pa_stateme_f245d5_idx',
            old_name='payments_stmtline_import_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentstatementline',
            new_name='payments_pa_externa_3698ae_idx',
            old_name='payments_stmtline_external_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentstatementline',
            new_name='payments_pa_amount_e13bb5_idx',
            old_name='payments_stmtline_amount_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payments_pa_payment_277486_idx',
            old_name='payments_pa_paymen_9c8c7b_idx',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='finance.contribution'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='failure_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='initiated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Payment provider name (stripe, flutterwave, safaricom, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='provider_intent_id',
            field=models.CharField(blank=True, default='', help_text="Provider's payment intent/session ID", max_length=255),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='purpose_id',
            field=models.UUIDField(blank=True, help_text='ID of the purpose object (contribution, fine, loan, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reference',
            field=models.CharField(default=apps.payments.unified_models.generate_payment_reference, help_text='Unique payment reference', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_reference',
            field=models.CharField(blank=True, default='', help_text='Payer reference (phone, card last4, bank ref)', max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_name',
            field=models.CharField(default='manual', help_text='Provider name (stripe, flutterwave, safaricom, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_reference',
            field=models.CharField(db_index=True, default=apps.payments.unified_models.generate_transaction_reference, help_text="Provider's transaction reference", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankpaymentdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankpaymentdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashpaymentdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashpaymentdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manualpaymentapprovalpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manualpaymentapprovalpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentactivitylog',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELLED', 'Cancelled'), ('STK_SENT', 'STK Sent'), ('C2B_VALIDATED', 'C2B Validation'), ('C2B_CONFIRMED', 'C2B Confirmation'), ('B2C_REQUESTED', 'B2C Requested'), ('CALLBACK_RECEIVED', 'Callback Received'), ('POSTED_TO_LEDGER', 'Posted To Ledger'), ('LOAN_DISBURSEMENT_REQUESTED', 'Loan Disbursement Requested'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('LOAN_REPAYMENT_POSTED', 'Loan Repayment Posted'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_REJECTED', 'Refund Rejected'), ('REFUND_PROCESSED', 'Refund Processed'), ('DISPUTE_OPENED', 'Dispute Opened'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('NOTIFIED', 'Notified'), ('FAILED', 'Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='idempotency_key',
            field=models.CharField(help_text='Idempotency key to prevent duplicates', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='intent_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='merchant_request_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='purpose',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('fine', 'Fine'), ('loan_repayment', 'Loan Repayment'), ('meeting_fee', 'Meeting Fee'), ('special_contribution', 'Special Contribution'), ('other', 'Other')], default='contribution', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('pending_authentication', 'Pending Authentication'), ('pending_verification', 'Pending Verification'), ('success', 'Success'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reconciled', 'Reconciled')], default='initiated', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentreconciliationcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliationcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreconciliationcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentreconciliationcase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsettlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsettlement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsettlementallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsettlementallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentstatementimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentstatementimport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentstatementline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentstatementline',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentstatementline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(default=apps.payments.unified_models.generate_transaction_reference, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='received', max_length=30),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['chama', 'status', 'payment_method'], name='payments_pa_chama_i_c1048d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', 'status', 'created_at'], name='payments_pa_user_id_ec9ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_0eb735_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_af49b9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['reference'], name='payments_pa_referen_544edd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_fb5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider_name', 'status'], name='payments_pa_provide_5a7340_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_7371e3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider_reference'], name='payments_pa_provide_ddbf17_idx'),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='payment_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesapaymentdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesapaymentdetails',
            name='payment_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='mpesapaymentdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cardpaymentdetails',
            index=models.Index(fields=['provider_intent_id'], name='payments_ca_provide_c8b05c_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapaymentdetails',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_3e4d24_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapaymentdetails',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_075812_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['payment_intent', 'created_at'], name='payments_pa_payment_993273_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['event', 'created_at'], name='payments_pa_event_2b7da7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='payments_pa_actor_i_f66efa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['receipt_number'], name='payments_pa_receipt_fee67b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['reference_number'], name='payments_pa_referen_c02fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['issued_at'], name='payments_pa_issued__70edc2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider', 'event_type', 'created_at'], name='payments_pa_provide_b79cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['payment_method', 'event_type'], name='payments_pa_payment_918b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider_reference'], name='payments_pa_provide_4a007e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['processed', 'created_at'], name='payments_pa_process_100de0_idx'),
        ),
    ]
