# Generated by Django 5.1.6 on 2026-04-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_cardpaymentdetails_mpesapaymentdetails_and_more'),
    ]

    operations = [
        # Drop the legacy card payment models directly. Intermediate RemoveField
        # operations trigger SQLite table rebuild issues due historical
        # constraints referencing removed columns.
        migrations.DeleteModel(
            name='CardPaymentAuditLog',
        ),
        migrations.DeleteModel(
            name='CardPaymentIntent',
        ),
        migrations.DeleteModel(
            name='CardPaymentReceipt',
        ),
        migrations.DeleteModel(
            name='CardPaymentTransaction',
        ),
        migrations.DeleteModel(
            name='CardPaymentWebhook',
        ),
    ]
