# Generated by Django 6.0.4 on 2026-04-26 00:33

import apps.payments.unified_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_receipt_download_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentreceiptdownloadtoken',
            new_name='payments_pa_payment_fa1299_idx',
            old_name='payments_prdl_pi_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceiptdownloadtoken',
            new_name='payments_pa_request_a5e598_idx',
            old_name='payments_prdl_user_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceiptdownloadtoken',
            new_name='payments_pa_consume_5fe7f0_idx',
            old_name='payments_prdl_consumed_idx',
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceiptdownloadtoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreceiptdownloadtoken',
            name='token',
            field=models.CharField(db_index=True, default=apps.payments.unified_models.generate_receipt_download_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentreceiptdownloadtoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsettlement',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentstatementimport',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
