# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("MEMBERS", "Members"),
                            ("CONTRIBUTIONS", "Contributions"),
                            ("FINES", "Fines"),
                            ("LOANS", "Loans"),
                            ("EXPENSES", "Expenses"),
                            ("INVESTMENTS", "Investments"),
                            ("MEETINGS", "Meetings"),
                            ("AUDIT_LOGS", "Audit Logs"),
                            ("PAYMENTS", "Payments"),
                            ("ALL_FINANCIAL", "All Financial Data"),
                            ("COMPLIANCE_PACK", "Compliance Pack"),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                ("field_order", models.PositiveIntegerField(default=0)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["dataset_type", "field_order"],
                "unique_together": {("dataset_type", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("MEMBERS", "Members"),
                            ("CONTRIBUTIONS", "Contributions"),
                            ("FINES", "Fines"),
                            ("LOANS", "Loans"),
                            ("EXPENSES", "Expenses"),
                            ("INVESTMENTS", "Investments"),
                            ("MEETINGS", "Meetings"),
                            ("AUDIT_LOGS", "Audit Logs"),
                            ("PAYMENTS", "Payments"),
                            ("ALL_FINANCIAL", "All Financial Data"),
                            ("COMPLIANCE_PACK", "Compliance Pack"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fields", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "export_format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("XLSX", "Excel"), ("PDF", "PDF")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="chama.chama",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("MEMBERS", "Members"),
                            ("CONTRIBUTIONS", "Contributions"),
                            ("FINES", "Fines"),
                            ("LOANS", "Loans"),
                            ("EXPENSES", "Expenses"),
                            ("INVESTMENTS", "Investments"),
                            ("MEETINGS", "Meetings"),
                            ("AUDIT_LOGS", "Audit Logs"),
                            ("PAYMENTS", "Payments"),
                            ("ALL_FINANCIAL", "All Financial Data"),
                            ("COMPLIANCE_PACK", "Compliance Pack"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fields", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "date_range_type",
                    models.CharField(default="LAST_30_DAYS", max_length=20),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day_of_week", models.PositiveIntegerField(blank=True, null=True)),
                ("day_of_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "export_format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("XLSX", "Excel"), ("PDF", "PDF")],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_exports",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExportPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("allowed_datasets", models.JSONField(default=list)),
                ("can_schedule", models.BooleanField(default=False)),
                ("can_view_all", models.BooleanField(default=False)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_permissions",
                        to="chama.chama",
                    ),
                ),
            ],
            options={
                "unique_together": {("chama", "role")},
            },
        ),
    ]
