# Generated by Django 5.1.6 on 2026-04-21 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chama", "0007_loanpolicy_block_pending_loan_applications_and_more"),
        ("finance", "0010_loanauditlog_loanapplication_approval_requirements_and_more"),
        ("issues", "0002_enhanced_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="issueattachment",
            name="issues_issu_issue_i_2d2a93_idx",
        ),
        migrations.RemoveIndex(
            model_name="issueattachment",
            name="issues_issu_uploade_2f195b_idx",
        ),
        migrations.RemoveField(
            model_name="issueattachment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="issueattachment",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="issueattachment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="issueattachment",
            name="uploaded_by",
        ),
        migrations.AlterModelOptions(
            name="issuerating",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issues_issu_chama_i_80010f_idx",
        ),
        migrations.RemoveIndex(
            model_name="issuecomment",
            name="issues_issu_issue_i_a3dfb7_idx",
        ),
        migrations.RemoveField(
            model_name="issuecomment",
            name="is_internal",
        ),
        migrations.RemoveField(
            model_name="issuecomment",
            name="message",
        ),
        migrations.AddField(
            model_name="issue",
            name="chairperson_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chairperson_approved_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueassignmenthistory",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueassignmenthistory",
            name="assigned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_assignments_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueassignmenthistory",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_assignments_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueassignmenthistory",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_history",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issueautotriggerlog",
            name="generated_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_trigger_logs",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="issueevidence",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueevidence",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issueevidence",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueevidence",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_evidences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuerating",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuerating",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuerating",
            name="rated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuerating",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuereopenrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuereopenrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_reopen_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuereopenrequest",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reopen_requests",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuereopenrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_reopen_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuereopenrequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolutions",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueresolution",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuestatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuestatushistory",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="issues.issue",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issueactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("status_changed", "Status Changed"),
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("clarification_requested", "Clarification Requested"),
                    ("clarification_provided", "Clarification Provided"),
                    ("comment_added", "Comment Added"),
                    ("evidence_added", "Evidence Added"),
                    ("investigation_started", "Investigation Started"),
                    ("investigation_update", "Investigation Update"),
                    ("resolution_proposed", "Resolution Proposed"),
                    ("resolution_approved", "Resolution Approved"),
                    ("resolution_rejected", "Resolution Rejected"),
                    ("resolution_executed", "Resolution Executed"),
                    ("dismissed", "Dismissed"),
                    ("escalated", "Escalated"),
                    ("vote_started", "Vote Started"),
                    ("vote_completed", "Vote Completed"),
                    ("warned", "Warned"),
                    ("suspended", "Suspended"),
                    ("suspension_lifted", "Suspension Lifted"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                    ("rated", "Rated"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="issueassignmenthistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issueautotriggerlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issueevidence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issueevidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuerating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuerating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuereopenrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuereopenrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issueresolution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issueresolution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuestatushistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="issuestatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("pending_assignment", "Pending Assignment"),
                    ("assigned", "Assigned"),
                    ("clarification_requested", "Clarification Requested"),
                    ("under_investigation", "Under Investigation"),
                    ("in_progress", "In Progress"),
                    ("resolution_proposed", "Resolution Proposed"),
                    ("awaiting_chairperson_approval", "Awaiting Chairperson Approval"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("escalated", "Escalated"),
                    ("in_vote", "In Vote"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="issuestatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending_assignment", "Pending Assignment"),
                    ("assigned", "Assigned"),
                    ("clarification_requested", "Clarification Requested"),
                    ("under_investigation", "Under Investigation"),
                    ("in_progress", "In Progress"),
                    ("resolution_proposed", "Resolution Proposed"),
                    ("awaiting_chairperson_approval", "Awaiting Chairperson Approval"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("escalated", "Escalated"),
                    ("in_vote", "In Vote"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["chama", "status", "severity"],
                name="issues_issu_chama_i_acb0d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["issue_code"], name="issues_issu_issue_c_6be366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["status", "created_at"], name="issues_issu_status_95f60a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecomment",
            index=models.Index(
                fields=["issue", "visibility"], name="issues_issu_issue_i_300169_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecomment",
            index=models.Index(
                fields=["issue", "comment_type"], name="issues_issu_issue_i_ec29ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueevidence",
            index=models.Index(
                fields=["issue", "created_at"], name="issues_issu_issue_i_1101f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueevidence",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="issues_issu_uploade_fc5aa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuerating",
            index=models.Index(
                fields=["issue", "rated_by"], name="issues_issu_issue_i_4992a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuerating",
            index=models.Index(
                fields=["rated_by", "created_at"], name="issues_issu_rated_b_7184d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuereopenrequest",
            index=models.Index(
                fields=["issue", "decision"], name="issues_issu_issue_i_ed4505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuereopenrequest",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="issues_issu_request_dc6d4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issueresolution",
            index=models.Index(
                fields=["issue", "status"], name="issues_issu_issue_i_4ad1bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueresolution",
            index=models.Index(
                fields=["proposed_by", "created_at"],
                name="issues_issu_propose_5836e1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuerating",
            constraint=models.UniqueConstraint(
                fields=("issue", "rated_by"), name="unique_issue_rating_per_user"
            ),
        ),
        migrations.DeleteModel(
            name="IssueAttachment",
        ),
    ]
