# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chama",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("subcounty", models.CharField(blank=True, max_length=120)),
                ("referral_code_used", models.CharField(blank=True, max_length=16)),
                ("referral_applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "chama_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("savings", "Savings"),
                            ("investment", "Investment"),
                            ("welfare", "Welfare"),
                            ("mixed", "Mixed"),
                        ],
                        default="savings",
                        max_length=20,
                    ),
                ),
                ("join_enabled", models.BooleanField(default=True)),
                ("join_code", models.CharField(blank=True, max_length=12, unique=True)),
                ("join_code_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "join_mode",
                    models.CharField(
                        choices=[
                            ("auto_join", "Auto Join"),
                            ("approval_required", "Approval Required"),
                        ],
                        default="approval_required",
                        max_length=24,
                    ),
                ),
                ("allow_public_join", models.BooleanField(default=False)),
                ("require_approval", models.BooleanField(default=True)),
                ("max_members", models.PositiveIntegerField(default=100)),
                ("setup_completed", models.BooleanField(default=False)),
                ("setup_step", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_chamas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChamaSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "join_approval_policy",
                    models.CharField(
                        choices=[
                            ("auto", "Auto Approve"),
                            ("admin", "Admin Approval"),
                            ("secretary", "Secretary Approval"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("meeting_day", models.PositiveIntegerField(default=5)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                ("voting_quorum_percent", models.PositiveIntegerField(default=50)),
                (
                    "voting_majority",
                    models.CharField(
                        choices=[
                            ("simple", "Simple Majority (>50%)"),
                            ("super", "Super Majority (>66%)"),
                            ("unanimous", "Unanimous"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=2)),
                ("late_penalty_type", models.CharField(blank=True, max_length=20)),
                (
                    "late_penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "chama",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chama Settings",
                "verbose_name_plural": "Chama Settings",
            },
        ),
        migrations.CreateModel(
            name="ContributionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Amount"), ("flexible", "Flexible")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("due_day", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_plans",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpensePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("allow_withdrawals", models.BooleanField(default=True)),
                ("allow_expenses", models.BooleanField(default=True)),
                (
                    "treasurer_admin_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        help_text="Amount requiring Treasurer+Admin approval",
                        max_digits=12,
                    ),
                ),
                (
                    "committee_vote_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Amount requiring committee vote",
                        max_digits=12,
                    ),
                ),
                (
                    "require_receipt_above_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        help_text="Receipt required above this amount",
                        max_digits=12,
                    ),
                ),
                (
                    "expense_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed expense categories",
                    ),
                ),
                (
                    "chama",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_policy",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Policy",
                "verbose_name_plural": "Expense Policies",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Invitee phone or email", max_length=255
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("requires_signature", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, default="", max_length=16)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("CHAMA_ADMIN", "Chama Admin"),
                            ("TREASURER", "Treasurer"),
                            ("SECRETARY", "Secretary"),
                            ("MEMBER", "Member"),
                            ("AUDITOR", "Auditor"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_chama_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chama_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InviteLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("requires_signature", models.BooleanField(default=False)),
                (
                    "preassigned_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("CHAMA_ADMIN", "Chama Admin"),
                            ("TREASURER", "Treasurer"),
                            ("SECRETARY", "Secretary"),
                            ("MEMBER", "Member"),
                            ("AUDITOR", "Auditor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approval_required", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("current_uses", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                ("restricted_phone", models.CharField(blank=True, max_length=16)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_links",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invite_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("loans_enabled", models.BooleanField(default=True)),
                ("min_contribution_cycles", models.PositiveIntegerField(default=3)),
                ("max_active_loans", models.PositiveIntegerField(default=1)),
                (
                    "loan_cap_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Max loan = this x total contributions",
                        max_digits=5,
                    ),
                ),
                (
                    "interest_model",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("reducing", "Reducing Balance"),
                            ("fee", "Fee Based"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Annual interest rate %",
                        max_digits=5,
                    ),
                ),
                ("require_guarantors", models.BooleanField(default=True)),
                ("min_guarantors", models.PositiveIntegerField(default=1)),
                ("require_treasurer_approval", models.BooleanField(default=True)),
                ("require_admin_approval", models.BooleanField(default=True)),
                ("require_committee_vote", models.BooleanField(default=False)),
                (
                    "penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        help_text="Late payment penalty % per month",
                        max_digits=5,
                    ),
                ),
                ("min_repayment_period", models.PositiveIntegerField(default=1)),
                ("max_repayment_period", models.PositiveIntegerField(default=12)),
                ("allow_early_repayment", models.BooleanField(default=True)),
                (
                    "early_repayment_discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "chama",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_policy",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Policy",
                "verbose_name_plural": "Loan Policies",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("CHAMA_ADMIN", "Chama Admin"),
                            ("TREASURER", "Treasurer"),
                            ("SECRETARY", "Secretary"),
                            ("MEMBER", "Member"),
                            ("AUDITOR", "Auditor"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("exited", "Exited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_chama_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations",
                        to="chama.membership",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_info", "Needs More Information"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_via",
                    models.CharField(
                        choices=[
                            ("public_join", "Public Join"),
                            ("join_code", "Join Code"),
                            ("invite_link", "Invite Link"),
                        ],
                        default="public_join",
                        max_length=20,
                    ),
                ),
                (
                    "phone_verified_at_approval",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("request_note", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.CharField(blank=True, max_length=255)),
                ("ai_decision", models.CharField(blank=True, max_length=30)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_risk_score", models.IntegerField(blank=True, null=True)),
                ("ai_recommendation", models.JSONField(blank=True, default=dict)),
                ("ai_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invite_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_requests",
                        to="chama.invitelink",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("provider_type", models.CharField(max_length=50)),
                ("mpesa_shortcode", models.CharField(blank=True, max_length=10)),
                ("mpesa_passkey", models.CharField(blank=True, max_length=255)),
                ("mpesa_callback_url", models.URLField(blank=True)),
                (
                    "mpesa_account_reference_format",
                    models.CharField(
                        default="CHAMA_{{chama_id}}_{{member_id}}",
                        help_text="Template for account reference",
                        max_length=50,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("allow_manual_entry", models.BooleanField(default=True)),
                ("manual_entry_requires_approval", models.BooleanField(default=True)),
                ("auto_reconcile", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_configs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Provider Config",
                "verbose_name_plural": "Payment Provider Configs",
            },
        ),
        migrations.CreateModel(
            name="RoleDelegation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("CHAMA_ADMIN", "Chama Admin"),
                            ("TREASURER", "Treasurer"),
                            ("SECRETARY", "Secretary"),
                            ("MEMBER", "Member"),
                            ("AUDITOR", "Auditor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_delegations",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegatee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_role_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(fields=["name"], name="chama_chama_name_29942e_idx"),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(fields=["status"], name="chama_chama_status_3953b2_idx"),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(
                fields=["county", "subcounty"], name="chama_chama_county_d3939f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(
                fields=["join_code"], name="chama_chama_join_co_447aff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(
                fields=["chama_type"], name="chama_chama_chama_t_b42698_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributionplan",
            unique_together={("chama", "name")},
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(
                fields=["status", "expires_at"], name="chama_invit_status_4d30ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(
                fields=["chama", "status"], name="chama_invit_chama_i_0ea903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitelink",
            index=models.Index(fields=["token"], name="chama_invit_token_34be27_idx"),
        ),
        migrations.AddIndex(
            model_name="invitelink",
            index=models.Index(
                fields=["chama", "is_active"], name="chama_invit_chama_i_e91c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitelink",
            index=models.Index(
                fields=["expires_at"], name="chama_invit_expires_f7052f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["status"], name="chama_membe_status_93cd0f_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["chama", "status"], name="chama_membe_chama_i_039e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "status"], name="chama_membe_user_id_c506ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["chama", "role"], name="chama_membe_chama_i_e2bed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["is_approved", "status"], name="chama_membe_is_appr_0d2d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["chama", "is_active", "is_approved"],
                name="chama_membe_chama_i_8ff4a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "is_active", "is_approved"],
                name="chama_membe_user_id_cd32c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["role"], name="chama_membe_role_331687_idx"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "chama"), name="uniq_user_chama_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), _negated=True),
                    ("is_approved", True),
                    _connector="OR",
                ),
                name="active_requires_approval",
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["chama", "status"], name="chama_membe_chama_i_09981c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["user", "status"], name="chama_membe_user_id_860b92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["expires_at"], name="chama_membe_expires_0b0802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["status", "reviewed_by"], name="chama_membe_status_174fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprequest",
            index=models.Index(
                fields=["requested_via", "status"],
                name="chama_membe_request_80b79b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "chama"),
                name="unique_pending_request_per_user_chama",
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["chama", "role", "is_active"],
                name="chama_roled_chama_i_e8976b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["delegatee", "is_active", "ends_at"],
                name="chama_roled_delegat_67fa40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roledelegation",
            index=models.Index(
                fields=["delegator", "is_active", "ends_at"],
                name="chama_roled_delegat_6bb3cb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="roledelegation",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="role_delegation_end_after_start",
            ),
        ),
    ]
