# Generated by Django 5.1.6 on 2026-03-31 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_loan_policy_recovery_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chamacontributionsetting',
            new_name='chama_chama_contrib_f4ff8c_idx',
            old_name='chama_contr_contrib_b3165c_idx',
        ),
        migrations.AddField(
            model_name='membership',
            name='can_invite_members',
            field=models.BooleanField(default=True, help_text='Whether member can invite new members'),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_request_loan',
            field=models.BooleanField(default=True, help_text='Whether member can request new loans'),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_vote',
            field=models.BooleanField(default=True, help_text='Whether member can vote on chama matters'),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_withdraw_savings',
            field=models.BooleanField(default=True, help_text='Whether member can withdraw savings'),
        ),
        migrations.AddField(
            model_name='membership',
            name='loan_default_risk',
            field=models.BooleanField(default=False, help_text='Flagged when member has overdue/defaulted loans'),
        ),
        migrations.AddField(
            model_name='membership',
            name='restriction_reason',
            field=models.TextField(blank=True, help_text='Reason for restrictions applied'),
        ),
        migrations.AddField(
            model_name='membership',
            name='restrictions_applied_at',
            field=models.DateTimeField(blank=True, help_text='When restrictions were last applied', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='restrictions_applied_by',
            field=models.ForeignKey(blank=True, help_text='User who applied the restrictions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['loan_default_risk'], name='chama_membe_loan_de_84a16f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['chama', 'loan_default_risk'], name='chama_membe_chama_i_33c17b_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['can_request_loan'], name='chama_membe_can_req_81b8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['can_withdraw_savings'], name='chama_membe_can_wit_38acbf_idx'),
        ),
    ]
