# Generated by Django 5.1.6 on 2026-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chama",
            "0006_rename_chama_contr_contrib_b3165c_idx_chama_chama_contrib_f4ff8c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpolicy",
            name="block_pending_loan_applications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpolicy",
            name="block_unpaid_penalties",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loanpolicy",
            name="guarantor_requirement_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amounts at or above this threshold require guarantors when guarantors are enabled.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loanpolicy",
            name="min_savings_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=5000,
                help_text="Minimum eligible member savings before borrowing is allowed.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loanpolicy",
            name="minimum_loan_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Minimum amount a member can request.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loanpolicy",
            name="repayment_capacity_ratio_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0.75,
                help_text="Maximum installment to average monthly savings ratio before borrowing is blocked.",
                max_digits=5,
            ),
        ),
    ]
