from django.urls import path

from . import views_dashboards

app_name = "dashboards"

urlpatterns = [
    path("", views_dashboards.dashboard_home_view, name="home"),
    # Dashboard Templates
    path(
        "superadmin/",
        views_dashboards.superadmin_dashboard_view,
        name="superadmin_dashboard",
    ),
    path("member/", views_dashboards.member_dashboard_view, name="member_dashboard"),
    path(
        "chama-admin/",
        views_dashboards.chama_admin_dashboard_view,
        name="chama_admin_dashboard",
    ),
    path(
        "treasurer/",
        views_dashboards.treasurer_dashboard_view,
        name="treasurer_dashboard",
    ),
    # Treasurer Dashboard Pages
    path(
        "treasurer/dashboard/",
        views_dashboards.treasurer_dashboard_view,
        name="treasurer_main",
    ),
    path(
        "treasurer/approvals/",
        views_dashboards.treasurer_approvals_view,
        name="treasurer_approvals",
    ),
    path(
        "treasurer/approvals/loans/",
        views_dashboards.treasurer_loan_approvals_view,
        name="treasurer_loan_approvals",
    ),
    path(
        "treasurer/approvals/withdrawals/",
        views_dashboards.treasurer_withdrawal_approvals_view,
        name="treasurer_withdrawal_approvals",
    ),
    path(
        "treasurer/approvals/disbursements/",
        views_dashboards.treasurer_disbursement_approvals_view,
        name="treasurer_disbursement_approvals",
    ),
    path(
        "treasurer/wallet/",
        views_dashboards.treasurer_wallet_view,
        name="treasurer_wallet",
    ),
    path(
        "treasurer/contributions/",
        views_dashboards.treasurer_contributions_view,
        name="treasurer_contributions",
    ),
    path(
        "treasurer/loans/",
        views_dashboards.treasurer_loans_view,
        name="treasurer_loans",
    ),
    path(
        "treasurer/loans/pending/",
        views_dashboards.treasurer_loans_pending_view,
        name="treasurer_loans_pending",
    ),
    path(
        "treasurer/loans/active/",
        views_dashboards.treasurer_loans_active_view,
        name="treasurer_loans_active",
    ),
    path(
        "treasurer/loans/overdue/",
        views_dashboards.treasurer_loans_overdue_view,
        name="treasurer_loans_overdue",
    ),
    path(
        "treasurer/disbursements/",
        views_dashboards.treasurer_disbursements_view,
        name="treasurer_disbursements",
    ),
    path(
        "treasurer/withdrawals/",
        views_dashboards.treasurer_withdrawals_view,
        name="treasurer_withdrawals",
    ),
    path(
        "treasurer/transactions/",
        views_dashboards.treasurer_transactions_view,
        name="treasurer_transactions",
    ),
    path(
        "treasurer/ledger/",
        views_dashboards.treasurer_ledger_view,
        name="treasurer_ledger",
    ),
    path(
        "treasurer/penalties/",
        views_dashboards.treasurer_penalties_view,
        name="treasurer_penalties",
    ),
    path(
        "treasurer/mpesa/",
        views_dashboards.treasurer_mpesa_view,
        name="treasurer_mpesa",
    ),
    path(
        "treasurer/reports/",
        views_dashboards.treasurer_reports_view,
        name="treasurer_reports",
    ),
    path(
        "treasurer/audit/",
        views_dashboards.treasurer_audit_view,
        name="treasurer_audit",
    ),
    path(
        "treasurer/notifications/",
        views_dashboards.treasurer_notifications_view,
        name="treasurer_notifications",
    ),
    path(
        "treasurer/ai/",
        views_dashboards.treasurer_ai_view,
        name="treasurer_ai",
    ),
    path(
        "treasurer/settings/",
        views_dashboards.treasurer_settings_view,
        name="treasurer_settings",
    ),
    path(
        "treasurer/security/",
        views_dashboards.treasurer_security_view,
        name="treasurer_security",
    ),
    path(
        "secretary/",
        views_dashboards.secretary_dashboard_view,
        name="secretary_dashboard",
    ),
    path("auditor/", views_dashboards.auditor_dashboard_view, name="auditor_dashboard"),
]
