# Generated by Django 5.1.6 on 2026-03-02 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chama", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("chama", "Chama"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_statement", "Member Statement"),
                            ("member_contributions", "Member Contributions"),
                            ("member_loans", "Member Loans"),
                            ("member_withdrawals", "Member Withdrawals"),
                            ("member_receipts", "Member Receipts"),
                            ("chama_summary", "Chama Fund Summary"),
                            ("chama_ledger", "Ledger Report"),
                            ("chama_contributions", "Contributions Report"),
                            ("chama_loans", "Loans Report"),
                            ("chama_payouts", "Payouts Report"),
                            ("chama_arrears", "Arrears/Delinquency"),
                            ("chama_audit", "Audit Report"),
                            ("chama_reconciliation", "Reconciliation Report"),
                            ("loan_statement", "Loan Statement"),
                            ("loan_monthly_summary", "Loan Monthly Summary"),
                            ("loan_schedule", "Loan Repayment Schedule"),
                            ("loan_approvals_log", "Loan Approvals Log"),
                            ("chama_health_score", "Chama Health Score"),
                            ("collection_forecast", "Collection Forecast"),
                            ("defaulter_risk", "Defaulter Risk"),
                            ("cohort_analysis", "Cohort Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_member_download", models.BooleanField(default=False)),
                (
                    "chama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_requests",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "status"],
                        name="reports_rep_request_46b951_idx",
                    ),
                    models.Index(
                        fields=["chama", "status"],
                        name="reports_rep_chama_i_c36a11_idx",
                    ),
                    models.Index(
                        fields=["report_type", "status"],
                        name="reports_rep_report__840842_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_rep_created_b07b87_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_statement", "Member Statement"),
                            ("member_contributions", "Member Contributions"),
                            ("member_loans", "Member Loans"),
                            ("member_withdrawals", "Member Withdrawals"),
                            ("member_receipts", "Member Receipts"),
                            ("chama_summary", "Chama Fund Summary"),
                            ("chama_ledger", "Ledger Report"),
                            ("chama_contributions", "Contributions Report"),
                            ("chama_loans", "Loans Report"),
                            ("chama_payouts", "Payouts Report"),
                            ("chama_arrears", "Arrears/Delinquency"),
                            ("chama_audit", "Audit Report"),
                            ("chama_reconciliation", "Reconciliation Report"),
                            ("loan_statement", "Loan Statement"),
                            ("loan_monthly_summary", "Loan Monthly Summary"),
                            ("loan_schedule", "Loan Repayment Schedule"),
                            ("loan_approvals_log", "Loan Approvals Log"),
                            ("chama_health_score", "Chama Health Score"),
                            ("collection_forecast", "Collection Forecast"),
                            ("defaulter_risk", "Defaulter Risk"),
                            ("cohort_analysis", "Cohort Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                        ],
                        default="json",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("is_async", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chama", "report_type", "created_at"],
                        name="reports_rep_chama_i_bf2bfa_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="reports_rep_status_eaf0aa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_statement", "Member Statement"),
                            ("member_contributions", "Member Contributions"),
                            ("member_loans", "Member Loans"),
                            ("member_withdrawals", "Member Withdrawals"),
                            ("member_receipts", "Member Receipts"),
                            ("chama_summary", "Chama Fund Summary"),
                            ("chama_ledger", "Ledger Report"),
                            ("chama_contributions", "Contributions Report"),
                            ("chama_loans", "Loans Report"),
                            ("chama_payouts", "Payouts Report"),
                            ("chama_arrears", "Arrears/Delinquency"),
                            ("chama_audit", "Audit Report"),
                            ("chama_reconciliation", "Reconciliation Report"),
                            ("loan_statement", "Loan Statement"),
                            ("loan_monthly_summary", "Loan Monthly Summary"),
                            ("loan_schedule", "Loan Repayment Schedule"),
                            ("loan_approvals_log", "Loan Approvals Log"),
                            ("chama_health_score", "Chama Health Score"),
                            ("collection_forecast", "Collection Forecast"),
                            ("defaulter_risk", "Defaulter Risk"),
                            ("cohort_analysis", "Cohort Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("chama", "Chama"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                    ),
                ),
                ("schedule", models.CharField(max_length=100)),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=20)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chama", "is_active"],
                        name="reports_sch_chama_i_9c836d_idx",
                    ),
                    models.Index(
                        fields=["schedule", "is_active"],
                        name="reports_sch_schedul_d141c6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatementDownloadHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("member_statement", "Member Statement"),
                            ("member_contributions", "Member Contributions"),
                            ("member_loans", "Member Loans"),
                            ("member_withdrawals", "Member Withdrawals"),
                            ("member_receipts", "Member Receipts"),
                            ("chama_summary", "Chama Fund Summary"),
                            ("chama_ledger", "Ledger Report"),
                            ("chama_contributions", "Contributions Report"),
                            ("chama_loans", "Loans Report"),
                            ("chama_payouts", "Payouts Report"),
                            ("chama_arrears", "Arrears/Delinquency"),
                            ("chama_audit", "Audit Report"),
                            ("chama_reconciliation", "Reconciliation Report"),
                            ("loan_statement", "Loan Statement"),
                            ("loan_monthly_summary", "Loan Monthly Summary"),
                            ("loan_schedule", "Loan Repayment Schedule"),
                            ("loan_approvals_log", "Loan Approvals Log"),
                            ("chama_health_score", "Chama Health Score"),
                            ("collection_forecast", "Collection Forecast"),
                            ("defaulter_risk", "Defaulter Risk"),
                            ("cohort_analysis", "Cohort Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "chama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_downloads",
                        to="chama.chama",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "chama", "created_at"],
                        name="reports_sta_user_id_a046f1_idx",
                    ),
                    models.Index(
                        fields=["report_type", "format", "created_at"],
                        name="reports_sta_report__be1ac8_idx",
                    ),
                ],
            },
        ),
    ]
