# Generated by Django 5.1.6 on 2026-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_cancellation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
    ]
