# Generated by Django 6.0.4 on 2026-04-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0007_loanpolicy_block_pending_loan_applications_and_more'),
        ('notifications', '0002_broadcast_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chama.chama'),
        ),
        migrations.AlterField(
            model_name='notificationeventthrottle',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_event_throttles', to='chama.chama'),
        ),
    ]
